### ISSUE TITLE
Link to new interactive environment does not work in anonymous mode

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1030]
## Description

I would like to provide anonymous users a link directly to the new environment launch page, so they can directly get to the feature they want, but this link brings up a login form.

  https://renkulab.io/projects/ROS/ROS-Examples/environments/new

Instead, it should take you the environment launch page. (It works correctly if you first go to https://renkulab.io/projects/ROS/ROS-Examples/environments and click new, but that is one extra step that is unnecessary).

**Comment by lorenzo-cavazzi** [comment]
I tried a few times and I got inconsistent results -- sometimes it happens and sometimes it doesn't.
Since the anonymous user triggers an "anonymous login" resulting in a quick refresh of the page, I suspect there may be an API triggering the login and it actually redirects only if the response is fast enough.

**Comment by lorenzo-cavazzi** [comment]
I think the culprit may be the API call to https://renkulab.io/api/notebooks/server_options generating a 401 if invoked early but working fine after the `login-tmp` has completed.
It's easy to reproduce in Chrome while it doesn't happen often on Firefox -- not sure why :thinking:
