### ISSUE TITLE
Simplify Dataset Create / Edit

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1116]
## Motivation

It is great that all the options for specifying dataset metadata are there, but it is a little overwhelming and unnecessary in many cases.

## Proposal

1. We should only show the Creator, Keywords, and Name fields if explicitly requested.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1196411/98394848-9fcc2100-205b-11eb-9bb8-05b435007fd3.png">
(The screenshot shows "Create", but "Edit" should work the same.)

2. The user should be set as the creator in a new dataset by default

3. Changing just the affiliation of a creator on the edit field does not seem to work.

**Comment by rokroskar** [comment]
Thanks @ciyer - a couple things:

* what is "name" in "do you want to specify the name"? 
* I would say "additional dataset creators" since the default creator is already set
* if the field for adding creators is shown, make sure it's clear that they are in addition to the existing creator
* I'm not sure we need to remove keywords from the default display - if they come under the description it's fine but maybe the element can be slightly smaller than what is there currently
