### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1167]
## Motivation

We want to improve the way we show notifications. Proposals are welcome.

We may want to let the user personalize a few parameters. For that to happen, we need this SwissDataScienceCenter/renku#712 , possibly revamped to use the renku-ui-server as the backend to store user-related settings.

## Mock-ups / Design

to-do

# Progress

- [ ] Design
- [ ] Implementation

**Comment by rokroskar** [comment]
From the current state of the notifications I think what I would like most is for them to be less obtrusive. I find the relatively large popup window maybe a bit too much and the animations (both of the display countdown bar and the actual popup disappearing) are not really needed imho. I'd prefer a subtle animation of the notification dot on the drawer that I think would probably be enough to draw your attention there. Specifically for the logout, my eye will already notice that I've been logged out because the top bar will be different, so I will naturally notice the notification drawer has something new to tell me and I'll go there. I know it will mean an extra click, but I have to click anyway to dismiss the notification so it doesn't really change anything. If you want to stick with some sort of popup I would really try to make it very minimal. Just my 2 rappen! :)

**Comment by lorenzo-cavazzi** [comment]
Making the toast notification less obtrusive can be done, but I guess the main problem is the toast itself.
I agree it's too much for the user, especially when the number of notifications grows. On the other hand, I think it's a useful mechanic to draw the user's attention when needed (e.g. with errors).

I'm wondering if it would make sense to create the toast only for errors, trying to limit those cases to whenever it's really necessary. For warnings and acknowledges, the +1 in the toast menu icon on the top bar should be enough.

**Comment by ciyer** [comment]
There are at least two different kinds of notifications that we want to present. One kind are "Alert" notifications. What distinguishes these are that the UI will change to reflect the information we are showing regardless of whether the user does something or not. The "You have been logged out" notifications is one such case. We can show these as toasts, but we could also show these as a splash over the content.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/1196411/101498830-d8b62900-396c-11eb-93ed-e100623f54c6.png">

The other kind of notification is an "Info" notification where we want to inform the user about some activity that they have initiated and is now ready. In this case, nothing will change in the UI until the user does something.

If we support notifications from GitLab, then we will have another kind of notification that comes from activity done by others on a project the user works on.

**Comment by lorenzo-cavazzi** [comment]
The idea is still interesting but we might want to move this to a ShapeUp pitch targeting the latest version of the platform. I'm closing the UI issue
