### ISSUE TITLE
Integration with data repositories

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#1313]
## Motivation

To facilitate the embedding of renku in data repository systems (e.g. [Dataverse](https://dataverse.harvard.edu/), it would be beneficial to have a way to bring data from those repositories into renku with minimal effort. Something like this has already been attempted with an easy-to-use [AiiDA template](https://github.com/SwissDataScienceCenter/contributed-project-templates/), but this still requires several manual steps on the part of the user. An example of such an integration is provided by the [Whole Tale project](https://wholetale.readthedocs.io/en/stable/users_guide/integration.html#analyze-in-whole-tale). 

## Proposal

As a user of the data repository, I would like to click a button and be taken to the equivalent of this dialog

![image](https://user-images.githubusercontent.com/3353586/114558599-228c8400-9c6b-11eb-99ed-839a5058e026.png)

which would allow me to select an _existing_ project to import the dataset into. Eventually, it would be nice if I could create a project on-the-fly if I didn't already have one available. 

The first target for such an integration should be Dataverse via their [external tools](https://guides.dataverse.org/en/latest/admin/external-tools.html#inventory-of-external-tools) functionality.

**Comment by ltalirz** [comment]
Thanks, @rokroskar - in a way, this is a generalization of what we're currently doing with the AiiDA approach: the topmost option in the dropdown should probably be "new project" and then would do what we're currently doing.

We'd certainly be happy to point to a different renkulab endpoint that allows for selecting an existing project instead of creating a new one.

One feature that might be end up being very useful is to highlight certain projects/project templates based on the file extension that already contain the necessary software environment for working with that data (as is the case with the AiiDA environment, for example).

**Comment by ltalirz** [comment]
P.S. Besides waiting for integration / links from the external data repositories, what about having on renkulab.io a page with:
 * a text input for a file URL
 * an "open in renkulab" button 
(could even fit on the renkulab.io landing page shown to logged-out users)

The default environment could have already the most common packages installed, and based on the file extension it might suggest a different environment by default.

**Comment by lorenzo-cavazzi** [comment]
We can now import data from external sources, and clone/import datasets into/from existing Renku repositories.
Mind that most of these concepts will be revised anyway in the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
