### ISSUE TITLE
Fail gracefully when a markdown can't be rendered

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1340]
## Description

It's been reported that when a markdown file can't be rendered the project becomes unusable...

It would be good to fail gracefully in these situations: when a markdown file can't be rendered we should just display an error message saying "The markdown file can't be rendered in renkulab" or something similar.

**Comment by lorenzo-cavazzi** [comment]
The issue seems to be addressed by some of the latest changes to the Markdown rendering. Errors are non-blocking in the latest release. Here is an example where a few images are missing:
https://renku-ci-ui-1274.dev.renku.ch/projects/lorenzo.cavazzi.tech/test-images

If anyone still experiences crashes on markdown files, please feel free to open a new issue, either with a link to a sample project or a description on how to reproduce it.
