### ISSUE TITLE
Side-by-side deployment of Renku new and old UIs

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1373]
# Description

For a transition period, we want allow people to try out the new UI while still leaving the existing UI as the default.

# Configuration / Deployment

There are several options to deploy the two UIs side-by-side.

1. Create a new k8s deployment (beta.renkulab.io) and deploy the new UI there

This would work similarly to how we do the personal dev deployments. beta.renkulab.io would be configured to share gitlab with renkulab.io, but it would have parallel infrastructure for everything else.

**Pros** Easy to set up, easy to run the Selenium tests against both UIs
**Cons** Different URLs for the two versions, cannot seamlessly switch (e.g., sessions started in the old UI would only be visible there)
**Assessment: This is probably the best approach if the resources we need are available.**

2. K8s canary deployment for the new UI

The new and old UIs would be available under the same URL, but a cookie would determine which UI the user gets routed to.

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary

**Pros** Can seamlessly switch between the new and old UI
**Cons** Some work necessary to get it set up; Selenium tests could be complicated

**Assessment: This is a bit more complicated than 1, but would probably work.**

3. Have both UIs available in the UI pod, use nginx to route to the appropriate UI

The new and old UIs would be available under the same URL and Nginx would look at a cookie to determine which one to serve.

~~https://www.nginx.com/blog/performing-a-b-testing-nginx-plus/~~
https://stackoverflow.com/questions/27376235/routed-traffic-with-cookies-nginx

Pros: All setup is restricted to the UI component, can seamlessly switch between the new and old UIs
Cons: Some work necessary to get it set up; Selenium tests could be complicated

**Assessment: About the same as 2 in terms.**

# Old UI Banner

We need to add a banner to the old UI to let people know that they can try out the new one.

![image](https://user-images.githubusercontent.com/1196411/120338172-43309c00-c2f4-11eb-83ca-7e94fff944e3.png)

# New UI Landing

We need to add a new transitionary landing page for the Renku UI that explains the big changes

(Design coming)

**Comment by ableuler** [comment]
I would vote against option 1, mostly for the KG parts. I don't think we can build the full graph for both deployments (is it @jachro), and having dataset search etc. yield different results might be confusing.

Option 2 and 3 are very similar. I might have looked up a bad link for option 3 (paid feature), but my basic point is that if nginx can do it at the ingress level, we can also do it at the level of the nginx that's running inside the UI pod. The advantage I see here is that it would all be within the hands of the UI and thus a bit easier to test on personal and dev environments and roll out to prod. However, it's true that it comes at the cost of building this image that can serve both versions.

**Comment by ciyer** [comment]
> Option 2 and 3 are very similar. I might have looked up a bad link for option 3 (paid feature), but my basic point is that if nginx can do it at the ingress level, we can also do it at the level of the nginx that's running inside the UI pod. The advantage I see here with option 3 is that it would all be within the hands of the UI and thus a bit easier to test on personal and dev environments and roll out to prod. However, it's true that it comes at the cost of building this image that can serve both versions.

The nginx option available to us is `split_clients` which allows routing based on the hash of certain variable values, but the final route picked is random. If we want to let the user pick which UI they want, we need to use the `sticky route` option, which is a paid feature.

**Comment by rokroskar** [comment]
The canary deployment done via the k8s ingress seems fine to me (option 2). The downside is that you'll still need both versions of the code in the UI repo and build two images. We will need to modify the chart templates to include a second deployment and service. I didn't quite understand in the k8s nginx ingress docs how you tell the ingress which of the services is the canary, but presumably that's a solvable problem.

**Comment by jachro** [comment]
Let me add something from my side. I agree option 1, keeping in mind our experience with envs sharing resources, seems to be looking like the easiest option. However, even from the conceptual point of view, I've got a feeling that deploying a complete parallel env just for a single component seems not to be the right thing to do. That's a feeling, though. From the practicalities, correct me if I'm wrong, but I don't think we do exactly this kind of set-up anywhere else. The reason is that in the proposed solution we'd need to share all the data between these two envs, which is not just GitLab but also Postgress and Jena (Redis?). The other thing is more from the KG sandbox. Internal KG services synchronize with each other in two ways: through the DB and REST calls. What that means. We can easily scale them up/down within an env but when we'd try to share the DB (Postgres is the key here) with cutting out the HTTP visibility, things will simply go crazy. Obviously, that might be changed but we were not designing KG in a way to work in such set-ups.

Both 2 and 3 looks to me by far better than 1. As Sekhar mentioned, both have their own pros and cons. Maybe to add smth to the cons side. For me adding something which would allow us for A-B testing is something not just for now but a feature we could benefit from in the future (especially that I think we have some friendly users who could be very happy to look at our new features or proposals). Of course, that option does not come for free and I think polishing it so to some satisfying levels of quality and confidence in 2-3 weeks time, sounds to me a bit challenging.

**Comment by ciyer** [comment]
I looked into it further, and it seems like we could do this in Nginx, but using a different method than the one that was originally linked to.
