### ISSUE TITLE
iframe for issues and merge requests don't appear

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1434]
## Description

The iframes which are supposed to show a gitlab view in the issues and merge requests don't show.

![image](https://user-images.githubusercontent.com/22785147/126970590-d7d189d2-282e-4fb6-b309-e17d22c69c2b.png)

## Reproduce

Occurs on (at least) both renkulab and dev

## Context

- renkulab url
- operating system and version
- browser and version 

<details><summary>Browser Output</summary>
<pre>
If possible, paste the output from your browser Javascript console here.
</pre>
</details>

![image](https://user-images.githubusercontent.com/22785147/126970879-8a12ccaa-af31-4243-8850-246cb4fff8bc.png)

(couldn't work out how to get the raw text output :( )

**Comment by ableuler** [comment]
While this can be fixed by adding corresponding ingress annotations when GitLab is part of the deployment, the UI should be able to handle the case where it can not embed GitLab gracefully as this might happen for cases where the Renku admins don't control the GitLab instance they're using.

**Comment by ciyer** [comment]
@ableuler Yes! We plan to do this, but we first need the ui-server component to enable this. See https://github.com/SwissDataScienceCenter/renku-ui/pull/1361#issue-653339396

**Comment by ciyer** [comment]
Thanks for pointing this out! The source of the problem was some k8s configuration that got lost when GitLab was upgraded. This should be addressed in https://github.com/SwissDataScienceCenter/renku/pull/2242 . The necessary annotations have been added to the renkulab and dev environments.

Longer term, we want to improve the UX when this happens, but it needs some changes in the backend in order to implement (see discussion above).
