### ISSUE TITLE
Download lineage output as SVG

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1437]
## Motivation

The display of lineage generated from workflows is great, however there is currently no good way of exporting the output, except for example screenshot. I would like to share the workflow output and perhaps even customise it (e.g. with illustrative images) for certain data inputs.

## Proposal

Allow a SVG download of the generated output.

## Context

![image](https://user-images.githubusercontent.com/22785147/127650933-85ab4479-f3f9-4afd-b6c8-37ee9c565e0a.png)

**Comment by ciyer** [comment]
This is related to #405.

**Comment by lorenzo-cavazzi** [comment]
The Lineage feature won't be further expanded since it won't be part of the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
