### ISSUE TITLE
RStudio popup windows blocked when displayed in iframe

### ISSUE THREAD

**Issue by phgrosjean** [SwissDataScienceCenter/renku-ui#1465]
## Description

With the new UI, the session is displayed in an iframe by default. This design does not allow popup windows. RStudio relies heavily on popup windows (e.g., git operations, pdf report viewer, switching to another project inside RStudio, ...) All these windows are currently blocked and RStudio seems frozen or the corresponding feature is not accessible. When it is switched into full view with the "Open in new tab" button, everything works as expected.

## Reproduce

1. Create a Renku project with the Renku/renkulab-r base template
2. Make sure to switch to the new UI
3. In the project, click "Start"
4. When RStudio appears in the iframe, edit somehow a file, say README.md and save changes
5. Go to the "Git" tab at right, stage the README.md file and click the "Commit" button
6. The Popup blocked dialog box appear. Clicking on "Try again" does not solve the problem

Thus, it is impossible to commit with the RStudio UI in iframe mode. Switching to full frame, the feature is working as expected. It is the same for several other RStudio functions that rely on popup windows for its UI.

## Solution

Either allow popup windows from sessions in iframe (hard to do?) or go back to full frame session, at least by default, if not completely. The iframe session is **not** a good idea for different reasons, imo.

**Comment by ciyer** [comment]
Thanks a lot for this feedback! 

As for your general comment, the decision to embed the sessions in iframes was also internally hotly debated and quite controversial. The less than perfect experience of iframes cannot be denied, but we have some features in the works that we wanted to offer to all kinds of environments (e.g., Jupyter and RStudio), and this is the only feasible way for us to do so, unfortunately. In the future, we would like to make this a preference so that users can have sessions open full frame by default if that is their preference.

That said, we are working to make the iframe experience as nice as possible, and we should be able to resolve this limitation quickly.n

**Comment by ciyer** [comment]
@phgrosjean Thanks for raising this issue and providing such an easy to follow explanation of the problem! 

We have managed to fix this (see screenshots below). We also have further enhancements planned to experience around the iframe-based sessions; we hope, that will continue to improve.

![image](https://user-images.githubusercontent.com/1196411/132005113-447cb658-e753-4e75-8349-bd8f9b6334e3.png)

![image](https://user-images.githubusercontent.com/1196411/132005179-4d2e146e-ac43-4ec0-bd87-13380aff9890.png)
