### ISSUE TITLE
UI for mounting S3 buckets

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1499]
## Motivation

Support https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/1536163850/2021-04-01+S3+Buckets+in+Renku+Design+Proposal

## Mock-ups / Design

![image](https://user-images.githubusercontent.com/1196411/134480864-3911eabc-5407-4f4a-80d1-01e6cd13b0cd.png)

![image](https://user-images.githubusercontent.com/1196411/134486923-1fc565aa-59d3-4d49-906f-2a04b1e785fa.png)
[](url)
## Implementation

The S3 configuration will probably be re-used, so we need to make it quick and convenient to re-enter data. There are a few options for this, ordered here from easiest to most work to implement:
1. Use autofill properties to ensure that the browser can store and autofill information
2. ~~Store S3 configurations in the browser using local storage. We also need a solution for picking a stored configuration then.~~
3. ~~Store S3 configuration on the server using per-user storage.~~
(2, 3 to be handled later)

We will do 1, and the input for the fields will be in a model dialog. The "Save" button on the modal will test and not return to the main UI unless testing was successful. On a failure, the error message is shown and the user can fix or cancel.

### Not displayed details
- A non-tested vs. tested S3 mount should be indicated (maybe green background for tested?)
- We should indicate the S3 mounts in the session list

## Questions

- If an S3 bucket has been configured, should we block starting until it has been tested?
- What happens if the S3 bucket fails to mount? Does the session start anyway? Can we show helpful feedback/error messages in this case (e.g., notification that S3 bucket could not mount, an indication in the session list that an S3 bucket was requested but not mounted)?

## Progress

- [ ] API Design (sprint-??)
- [ ] UI Implementation

**Comment by lorenzo-cavazzi** [comment]
I would force the user to test the S3 bucket before adding it to the list -- e.g. a `test` button and an `add` button that is grayed out until it's tested, or even name the second button `test and add` so that the 2 operations will happen in sequence.

For the storage option, I guess the 2nd is reasonably easy but I'm not sure it's the safest option. The session storage should be ok to store sensitive information ([reference](https://html.spec.whatwg.org/multipage/webstorage.html#sensitivity-of-data)), but not exactly meant to store passwords or any data related to authenticated users ([reference](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#local-storage)).
