### ISSUE TITLE
Adapt UI to warn users of disruptions due to 0.10.0 Renku release

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#1524]
The release of Renku 0.10.0 will require all existing user sessions to be removed. Therefore we need a way to communicate this to as many users as possible.

Can the Statuspage banner be made more prominent for a couple of days?
Can we use customized messaging in the banner?

**Comment by ciyer** [comment]
> This sounds good. Regarding point 3., at the beginning I have thought about us displaying the description instead or a custom message but description would be too long to display. We will need to use the title as a means to write what the user needs to do/be aware off (and not really what the maintenance is about). Not sure if we can do better though. Hopefully this change will reach more users.

Yes, the problem is that statuspage.io does not provide much else in the way of tools to provide and structure information. Other than the name, we could do something like the the "message" from the most recent (or oldest) update, but I think that is even more hacky.

> Do you plan to make this a permanent change? if so, we would not want to schedule further maintenance too much in advance, otherwise it will be too invasive, especially if no action from the user is needed or if there will be minimal disruption.
> 
> Ideally, we would have a way of specifying the level of alertness the users need to give to the message. If set, the information will be displayed in all pages if not, mimic the previous behavior (default). We could add this setting e.g. via UI values in a deployment. WDYT?

I think it would be nice to be able to control how invasive the status message is. The best solution would be to have that information stored in statuspage.io, but that would require either using some agreed-upon structure for the messages, or creating special statuspage.io "components" for that purpose and hard-coding specific meanings to specific components, which isn't very nice.

Controlling it from k8s is not a bad way to handle it, but we currently have no way of pushing changes to the values to running UIs. Users that connect to the UI or refresh would get the updates, but already connected users would not see these changes. Once we have the ui-server deployed and the push-notifications set up there then we could take advantage of that to solve this problem.

**Comment by pameladelgado** [comment]
> For the time being, let us use a special component to indicate if the message should have normal or higher visibility. Should we call the component Loud?

Perfect, thanks!
