### ISSUE TITLE
Decrease page size in gitlab `/projects` request

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#1528]
The discussion about GitLabs GraphQL endpoint and wether it could help to reduce the initial loading time made me have a look at the actual requests which are made when loading the landing page. I noticed that it is predominantly this request which takes a very long time to execute (around 7 seconds for me):

`https://renkulab.io/api/projects?order_by=last_activity_at&per_page=100&membership=true&page=1`

Making the same request in curl and reducing the page size from 100 to 10 brought the execution time of the query down by a factor of ~7 for me. Thus I think it would be really good to reduce the page size for all gitlab queries, not just to reduce the time of an initial page load from the clients perspective, but also to reduce the load on the GitLab server (which we can not just scale up that easily at the moment).

ps: the query for starred projects is much faster, presumably because I don't have many starred projects. So for the majority of users which do not have too many projects of which they are members, the loading time of the landing page shouldn't be that bad either.

**Comment by ableuler** [comment]
On a second look, one point that I don't understand is that - despite the large page size - the UI always issues a request for the second page right away and will show the loading dots until the response to the request for the second page has arrived too, despite the landing page only displaying 4 of my projects, even on a rather large screen. This increases the time during which the jumping dots are displayed to 10 seconds for me on renkulab.io

**Comment by ciyer** [comment]
> On a second look, one point that I don't understand is that - despite the large page size - the UI always issues a request for the second page right away and will show the loading dots until the response to the request for the second page has arrived too, despite the landing page only displaying 4 of my projects, even on a rather large screen. This increases the time during which the jumping dots are displayed to 10 seconds for me on renkulab.io

Yes, exactly. I think the underlying problem is that we keep a list of `userProjects` in the state, and we use these for multiple things. The userProjects is used for the landing page, but it is also used to do realtime validation on the new project name for a fork. In the second case, we need all the projects for the user (at least their full paths), but in the first, we only need a small number of projects.

Our plan is to only get a small number of projects for the landing page, and to only get the full path for a large number of projects for things like fork validation or quick-nav to a project. That is the plan laid out in https://github.com/SwissDataScienceCenter/renku-ui/issues/1505 and that should improve performance without losing functionality.
