### ISSUE TITLE
Create a new project based on a dataset

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1604]
## Motivation

It is possible to _add_ a dataset to a project, it would be nice to add an option to **create** a new project and add the dataset.

## Proposal

The add button, which currently opens a popup, should change. It should open a **new page** that lets the user either pick an existing project or create a new project, using the new project form.

![image](https://user-images.githubusercontent.com/1196411/148747250-481e66b1-7a20-4682-84df-8c87c0e30bb1.png)

If a new project is created, that should be the first step, the second step is to add the dataset to the project.

- We may want to show some more information about the dataset than just the title in this new form.

**Comment by lorenzo-cavazzi** [comment]
The `AddDataset` button currently uses the FormGenerator for the Autosuggest element.
The logic is a bit overcomplicated since we are not taking advantage of the draft (it's a single value for selecting the target project).
It would make sense to remove the FormGenerator login and to add the Autosuggest element directly there.

We should refine the whole logic by adding the following steps:
- [ ] Verify that the projects list is available before allowing the users to interact with the Autosuggest (use the fetched/fetching variables for member projects).
- [ ] Verify the status of the project containing the dataset:
  - It should exist in GitLab (it may not be the case! datasets are still there even when the underlying project is gone)
  - It should have a supported project metadata version
- [ ] Verify the status of the target project
  - It should have the very same metadata version of the origin project
- [ ] _OPTIONAL_: create a separate GraphQL query to get the member projects with relative permissions, and remove the permissions from the current one. Invoke the new one (with permissions) only when loading the AddDataset component. This would improve the performance quite a bit, since getting the permissions is time-consuming and not necessary anywhere else.
