### ISSUE TITLE
Hard reload is needed to get new UI

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#1650]
Browser:
![image](https://user-images.githubusercontent.com/13014091/150328770-0aa6dc7d-eabe-46cc-88c2-e3d9ceba1d4c.png)

Clicking the advertised button doesn't suffice, I have to hard-reload in order to get the new UI and make the banner go away.
![image](https://user-images.githubusercontent.com/13014091/150328594-c79705a8-f6aa-4801-b12c-e510f86b3d1b.png)

**Comment by lorenzo-cavazzi** [comment]
I suspect the problem is different here since the minified JS files now change for sure when a new version is available, hence the cached page should not be valid anymore.

My guess is that, after the update, there is still one (or more) older UI pods, and refreshing may result in getting the content served by the same UI instance. Also, the outdated UI server pods may be around for a little while, and that would result in the same message.

This would also explain why it's not easy to reproduce this in a test environment with a single pod, if not for a very few seconds in the case the UI server is already up-to-date and the newer UI client pod is still starting -- that is usually the case when updating an already running deployment with single pods (the UI server is very fast to come up in that case)

**Comment by lorenzo-cavazzi** [comment]
More details in the new issue #1876
