### ISSUE TITLE
Adjust the project name after project creation

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1685]
## Description

The project name is not set properly when creating a new project.
This happens because the renku-core API creates the project through a `git push` to GitLab, and some properties cannot be set through that. As a result, the GitLab project name is the project path.

## How to fix

After creating the project, we should immediately update the project name (if different from the project path) with the one specified by the user.
We already do something similar for the project visibility.

Info: we can easily verify if desired name and the **effective** path by checking the project creation API response. The path is returned as `slug`.

```
{
  "result": {
    "name": "test with spaces 4",
    "url": "https://dev.renku.ch/gitlab/lorenzo.cavazzi.tech/test-with-spaces-4",
    "project_id": "0436a56f63f245fe971e6484d6e1a474",
    "namespace": "lorenzo.cavazzi.tech",
    "slug": "test-with-spaces-4"
  }
}
```

## Reproduce

Try to create a project with spaces. The final name in the UI will contain only `-`.
Doing that directly on GitLab preserves the names.

**Comment by ciyer** [comment]
I propose that we punt on this. 

The problem is that the name in GitLab is incorrect (see https://dev.renku.ch/projects/lorenzo.cavazzi.tech/test-with-spaces-2).

But the Renku project metadata is correct:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1196411/153384795-3063fbd6-749d-4483-a06a-99101974475e.png">

We plan to soon switch to using the KG as the source of information about projects. This problem will then fix itself.
