### ISSUE TITLE
Rendering inline math formulas

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1719]
## Description

It seems there are still issues with rendering inline math, even after #1622

## Reproduce

This is a sample with a couple of formulas in the readme
https://renkulab.io/projects/lorenzo.cavazzi.tech/math-formulas

They are not rendered when using the inline notation, but they are when put inside a code block.
GitLab seems to always render them correctly (on the right in the Screenshot)

![Screenshot_20220303_173313](https://user-images.githubusercontent.com/43481553/156608891-15b367b3-346c-49a9-b924-58362535da59.png)

**Comment by lorenzo-cavazzi** [comment]
This is still actual even after the changes in #2136
We should give it a closer look.
Example: https://dev.renku.ch/projects/lorenzo.cavazzi.tech/another-math-formula

**Comment by lorenzo-cavazzi** [comment]
Another linked issue: #1125

**Comment by tomashco** [comment]
I've opened a PR that solves this problem and also the [2308](https://github.com/SwissDataScienceCenter/renku-ui/issues/2308)

The problem was not related to online formulas not working correctly (i.e. test it with $`E=mc^2`$) but with the underscores contained in it, which were converted as <em>, breaking the markdown convertion to html.
