### ISSUE TITLE
Renku down page when user is not authenticated

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#1759]
## Description

The interface is displaying a Renku down page when the user is not authenticated, it redirects to login automatically but this page is visible to the user for a few seconds.

## Reproduce

1. Go to renkulab.io or dev.renku.ch when you are not yet authenticated
2. See error 'Renku down'
![renkulab down when user is not authenticated](https://user-images.githubusercontent.com/43388408/160344269-6fc089ef-e99c-4541-938b-f54f1190c584.png)

**Comment by lorenzo-cavazzi** [comment]
This happens when the user was authenticated and the credentials expired.
We should probably update [the code here](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/user/User.state.js#L50-L67) to handle the `API_ERRORS.authExpired` case, and/or update what we display in that case instead of just showing the `Unavailable` class https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/App.js#L208-L210

P.S: on dev that happens frequently since the user credentials expire quickly. On RenkuLab, they last several days so this occurs rarely.
