### ISSUE TITLE
Redefine the UX around sessions (design)

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1805]
## Motivation

The UX around sessions has become a bit confusing for the users (E.G: see #1777 , #1800 ).
Specifically, it's not clear to the users what the content of the session will be.

Currently, we give priority to:
* Running sessions
* Autosaves
* Lastest commits

## Proposal

We need to:
* Show feedback when we detect an autosave and plan to load it
* Allow the user to quickly discard the autosave
* Show better feedback for `autostart`, especially when we find a running session

And, while making these changes, we also want to take better advantage of the screen real estate.

### Basic Flow

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/1196411/168064005-9ca268cb-8b6f-4911-9958-422487c6ea50.png">

### Autosave Flow

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/1196411/168085621-1163e5dc-d30d-4ae0-a89f-7fae0e2cced5.png">

After starting, the session should indicate that it was started from an autosave, and should have a link to your session help page describing how to manage unsaved information (e.g., push it to a new branch).

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1196411/167123721-3fbc1739-282b-4fb3-a585-eaf9147dd84a.png">

### Docker image not available

<img width="968" alt="image" src="https://user-images.githubusercontent.com/1196411/167124010-c8d35667-034f-4721-a012-06b6ef223285.png">

### Permissions limitations

<img width="963" alt="image" src="https://user-images.githubusercontent.com/1196411/167124046-bbfe9cfd-a753-4bc7-93d8-9395162504b2.png">

**Comment by andre-code** [comment]
Ux suggestions:
- [ ] If the current branch has an autosave commit, show "Start with options" as default, otherwise just "Start".
- [ ] Use the alert component to show extra information in case of autosave or in case of unavailable docker image. Include a floating effect in that area of the form so that it is always visible. Also show an alert hint before the submit button for these cases.
- Make explicit the information for autosave in the session view. e.g. Started from an autosave commit....
- [ ] Make explicit information about why the start button is disabled and the user has to start with a base image option. e.g. The docker image is not available, it is only possible to start session with a base image.

**Comment by ciyer** [comment]
Great suggestions! For the first point (If the current branch has an autosave commit, show "Start with options" as default, otherwise just "Start"), I think there are a few additional ideas we should consider as well:

- Use a tooltip to indicate that there is autosave information
- Change the label to "Start (continue)" or something to indicate that there is an autosave
