### ISSUE TITLE
Reduce internal links opening a new tab

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1835]
What buttons are they referring to? Do they mean the documentation buttons? If so, make separate task in the `renku` repo (not the `renku-ui` repo) to move docs to RenkuLab.

**Acceptance Criteria**
- [ ] Compile list of where html link `target=”_blank”` is in attribute from links
- [ ] Make appropriate issue(s) if there are ones we should change

**Comment by lokijuhy** [comment]
Oksana: Check ourselves instead of paying for Coteries

**Comment by ciyer** [comment]
I looked at all the links that open in new tabs. There are hundreds of these, but they all fall into one of the following categories:

1. Link leads outside the renkulab deployment
2. Link leads to the GitLab instance of the renkulab deployment
3. The action supports a user request to open the content in a new tab (e.g., open a session in a new tab instead of iframe)

So there are no internal links that open in a new tab, excluding those where this behavior is explicitly requested.
