### ISSUE TITLE
Add an action button to the datasets page (when the user is not logged in)

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1836]
**Acceptance Criteria**
- [ ] a "Start a project with this dataset" button on datasets page is visible to users when they are not logged in, which takes them through the log in / create account process

**Comment by lokijuhy** [comment]
Decided to proceed with first option - Log in/Create account and create new project with dataset

**Comment by lorenzo-cavazzi** [comment]
If you agree, I would keep this in line with other pages with access restricted to logged users (E.G: try accessing the following page from an incognito tab https://dev.renku.ch/projects/new ). Selecting "New project" will then show a similar message instead of the form, and the same goes for "Existing project" with slightly different text.

![image](https://user-images.githubusercontent.com/43481553/170221467-5e8f246f-7d7a-4d33-9eff-b7c7ec378827.png)

I guess having a coherent style everywhere would also help (E.G: the following page shows a similar feedback, but the `Log in` action is not inside an alert https://dev.renku.ch/projects/lorenzo.cavazzi.tech/flights-tutorial-2022-04-19/settings/sessions ).
I'll double-check that too.
