### ISSUE TITLE
remove unneeded calls to gitlab graphql on the dataset view page

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#1912]
On the dataset view page (e.g. https://renkulab.io/datasets/5cbf90e140fd49b88789c659f5a499a8) the only API call needed is https://renkulab.io/ui-server/api/kg/datasets/5cbf90e140fd49b88789c659f5a499a8 - instead there are a number of calls to the core service and gitlab that are made, slowing down the page render. We should eliminate these extra calls as much as possible.

**Comment by ciyer** [comment]
When you are on the project > datasets list page and navigate to one of the datasets, the UI is responsive only makes two calls.

<img width="992" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/e3138374-553f-4f2b-935c-8259c627394e">

The problem comes more from retrieving a bunch of information about project and datasets in general when navigating directly to a dataset page.

**Comment by lorenzo-cavazzi** [comment]
Let's try to remove the early query to `https://renkulab.io/datasets/5cbf90e140fd49b88789c659f5a499a8`

**Comment by andre-code** [comment]
This Issue is closed because it is no longer reproducible in the current code base. Upon review, we found that the issue was probably addressed when refactoring dataset components https://github.com/SwissDataScienceCenter/renku-ui/issues/2415
