### ISSUE TITLE
Automate generation of cheatsheet based on renku-python

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-ui#1920]
renku-python has [its own Sphinx directive](https://github.com/SwissDataScienceCenter/renku-python/blob/develop/docs/_ext/cheatsheet.py) to allow adding cheatsheet entries in the rp docs directly.

Cheatsheet entries currently look like 
```
.. cheatsheet::
   :group: Workflows
   :command: $ renku workflow ls
   :description: List Plans (workflow templates).
   :extended:
```
Where `Group` is the section header for an entry, `command` is the command in question, `description` describes the command and `:extended:` (if set) means this entry only shows up in the extended cheatsheet. Basic/important commands don't get `extended` set, and commands with `extended` set don't get included in the main cheatsheet. The pdf generated for renku-python includes extended entries, it is a sphinx option that can be set in sphinx's `conf.py` to toggel inclusion.

The custom directive currently supports latex (for pdf generation) and html (currently unused) builders.

it should be trivial to add support for the [JSON Builder](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinxcontrib.serializinghtml.JSONHTMLBuilder) as well in the directive, then `sphinx-build -b json -c docs/cheatsheet/ docs docs/json/ -W` would create JSON files for the cheatsheet, which could then be used to generate the cheatsheet in the UI/Sessions page.

This way, UI and renku-python cheatsheets will always be in sync without additional work required on the UI side.

Open questions:
- Would the `:extended:` flag suffice to filter out only relevant entries for the UI cheatsheet, as you probably don't want all commands (or maybe we do want all but have extended in a subsection somewhere at the end?)
- The grouping/topics between UI and CLI cheatsheets differ (e.g. "Datasets" in rp vs. "Managing contents" in ui), we'd need to think of a way to consolidate them/specify both in the directive
- We'd need to have a process in place where rp syncs with UI when adding a new cheatsheet directive in rp docs

Alternatives:
UI could provide a command reference style documentation that consumes the extended cheatsheet directly alongside its simplified cheatsheet.

**Comment by andre-code** [comment]
Currently we have 2 versions of the cheat sheet, one displayed in the UI and one as a PDF generated by renku-python.
Some ideas come from renku-python and renku-ui and is to include some of the UI groups in the PDF, and also select some important commands from the PDF to keep the UI simple.

Groups that would not appear in the UI:
- Getting Started
- Misc
- Config

Groups to include in the PDF: 
- Typical flow `git status`  `renku save -m <msg>`  `renku run …`
- Undo Renku Command `git reset --hard HEAD^`
- Saving Progress on a project `git status`  `renku save [-m <message>]`

Commands to include in the UI: to be defined.

Groups that only make sense in the UI:
- Autosave commands
- Collaboration

The goal is to keep the UI updated if a command changes or if a new command is added, then import those commands from python in json format.

The format would be:
```
{
   "groups":[
      {
         "name":"Dataset",
         "commands":[
            {
               "command":"renku dataset create <dataset>",
               "description":"Create a new dataset.",
               "extended":true
            },
            {
               "command":"$ renku dataset ls",
               "description":"List all datasets in the project.",
               "extended":true
            },
            {
               "command":"$ renku dataset rm <dataset>",
               "description":"Remove a dataset.",
               "extended":true
            }
         ]
      }
   ]
}

````
ORDES what do you think would be the best way to structure groups and commands for the UI and PDF?
Here are the current options
UI:
![Screenshot 2022-07-05 at 15 08 01](https://user-images.githubusercontent.com/43388408/177335044-b98f9f08-7b86-4e4e-8234-5c697be4cbea.png)


PDF: https://renku-python.readthedocs.io/en/latest/_static/cheatsheet/cheatsheet.pdf

**Comment by gavin-k-lee** [comment]
I'm slightly confused by the two cheat sheets - so on the UI one, the link at the bottom "Want to learn more ... cheat sheet" <- that cheatsheet links to the Renku Python one?

Some comments on the structure/contents of the UI one:
- **Typical Workflow** is basically duplicated with **Saving Progress on a Project** so we could just remove the second one.
- Is there any reason why `renku run` is duplicated from the **Typical Workflow** and also **Running and Tracking Commands**?
- I might rename **Managing Contents** to **Working with Renku Datasets** to emphasise the fact that these are Renku concepts. I would also capitalise any instance of "dataset" when "Renku Dataset" is meant since we do get confused users around this.
- This is more of a Renku Python question: for the purposes of undoing Reku runs, is `renku workflow revert <activity ID>` equivalent to `git reset --hard HEAD^`? If so, maybe this `workflow revert` is preferable since the title is "Undo Renku Command" 
- The **Autosave** section is a bit confusing if you don't know what they are - I know this section is referring to when you start a project from a previous git commit and there are unsaved changes, but I might rename it differently, perhaps "Tracking where you are in the Git history" or something like that.

With regards to the RP cheatsheet - I think it is fine as it is since the way one would come across this second cheatsheet is through the UI one? If that is the case then the UI ones would have already been seen, at least partially, by the user.

**Comment by gavin-k-lee** [comment]
Some comments from Cyril:
- We should also add `renku dataset import` in the Datasets section
- The last command in autosaves is probably too complicated for a cheatsheet
- A new Renku command `renku rollback` could be added instead of f `git reset --hard HEAD^` 

@Panaetius `renku rollback ` could probably be added to the RP cheatsheet too.

**Comment by gavin-k-lee** [comment]
Looks great! Thanks
