### ISSUE TITLE
Show maintenance message from statuspage (if present) on "renkulab down" page

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#1954]
It would be nice to show maintenance messages when a maintenance is active in the "renkulab down" page.

Currently there is a scheduled maintenance on renkulab. But because components are not available (due to the scheduled maintenance) going to renkulab.io shows only the generic "renkulab down" page. There is nothing wrong with this page but it would be nice to conditionally insert a section that shows the maintenance message (if one is active) inside the renkulab down page.

Because for a user that hasn't seen the prior notifications and just comes to renkulab.io it seems like there is an unexpected outage. And users would have to know / remember where the status page for renkulab (or other deployment is) so that they navigate to it and see whether the outage is planned or not.

![image](https://user-images.githubusercontent.com/16360283/178768800-ae96c413-7852-4898-bce5-499020ab6ec3.png)

**Comment by olevski** [comment]
An even better option is to have a dedicated maintenance page. That says clearly something along the lines of "We are doing maintenance right now, we should be back up and running soon" and below that we show the status page message or smth.

**Comment by lorenzo-cavazzi** [comment]
I agree it would be nicer to show maintenance data.
We actually show the "RenkuLab Down" as soon as we can't verify the user. That is the first step since we can't know for sure which page to display in some cases (E.G. anonymous landing page vs "logged in" landing).

Now that we use StatusPage, we could actually invoke the StatusPage API in parallel (or just after showing the RenkuLab Down page). If we get data about maintenances and any of them are supposed to happen in that moment, we can show the text so that users have some details (and know it's a scheduled maintenace).
