### ISSUE TITLE
Try storybook testing

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2163]
Cypress 11 now integrates well with Storybook.
We should try to refresh Storybook to keep track of the standard components we use in the UI and try using it for testing components

**Comment by lorenzo-cavazzi** [comment]
This needs https://github.com/SwissDataScienceCenter/renku-ui/issues/2128

**Comment by ciyer** [comment]
I investigated this, and I do not think this is ready for prime time yet. The most promising integration is the one teased here https://www.cypress.io/blog/2021/05/19/cypress-x-storybook-2-0/ , but the more polished integration promised in the post has not yet arrived. I think the better approach is to use Cypress component testing for now. Having a Storybook for the components is good, since that means that the component can easily be deployed in isolation, but I don't think we need to leverage Storybook more than that for the moment.

**Comment by lorenzo-cavazzi** [comment]
We can close this. The follow-up issue is #2212
