### ISSUE TITLE
Server Notifications Middleware

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#225]
We should identify a messaging middleware to deploy in the backend which will be used for queuing notifications from multiple sources. Asynchronous delivery of notifications to the UI (e.g., using WebSockets) would be nice, alternatively, we could poll for notifications, which would still be an improvement, since we only have one endpoint to poll.

The first target is to migrate the notebook service to provide status updates using this middleware.

# References

* https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/740818995/2020-09-02+Architecture+Review
* https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/695140361/Renku+Platform+events
* https://redislabs.com/blog/how-to-create-notification-services-with-redis-websockets-and-vue-js/

## Frameworks

(Not sure this is the best issue for this, but I wanted to make a note of these somewhere)
* https://github.com/graphql/express-graphql (see also the libraries that it builds on)

**Comment by lorenzo-cavazzi** [comment]
I thought a little bit about a solution to enable a live UI without polling and I came to this possible solution.

The idea requires 2 elements:

* WebSocket connection to get live information from the backend about possibly relevant changes
* Single redux store holding all the relevant shared data

The structure of the store should take into account a division in different topics to simplify refreshing the information.
Every refreshable block of information should have some metadata to make it clear if data are available and up-to-date. We could probably limit to 3 (even 2) properties

* fetched [timestamp]: if null, no data are available for the topic, otherwise last download timestamp
* fetching [bool]: wheater or not the data are being refreshed
* valid [bool]: if data are valid or not. After some toughts, I think we can get rid of this. When data are not valid anymore, we can simply set `fetched=null`

this is a stub of a possible store implementation

```
const reduxStore = {
	user: {
		_meta: {
			fetched: 2019-07-19T11:52:43Z,
			fetching: false
		},
		id: 23,
		state: "active",
		identities: [{
			provider: 'oauth2_generic',
			extern_uid: '8925a18e-056c-4e53-b37f-cf11957fa433'
		}]
		...
	},
	project: {
		_meta: {
			fetched: 2019-07-19T11:53:18Z,
			fetching: false
		},
		id: 95,
		namespace: "lorenzo.cavazzi.tech",
		branch: "master",
		statistics: {
			commit_count: 14,
			storage_size: 675542
		},
		commits: {
			_meta: {
				fetched: 2019-07-19T11:53:24Z,
				fetching: false
			},
			list: [{
				author_name: "Lorenzo",
				id: "c331b417f63a"
			}, {
				author_name: "Lorenzo",
				id: "17f63a244762"
			}]
		},
		graph: {
			_meta: {
				fetched: null,
				fetching: false
			},
		},
	},
}
```

In this example the websocket channel can notify us about changes for these 4 topics: `user`, `project`, `project.commits`, `project.graph`.
Intuitively, updates to `project.graph` can be ignored since we don't have data yet, but what about changes for the other topics, should we always refresh them?

If we associate to each route a list of useful topics, we can always know if we need to re-fetch data immediatly or not. In this example we can have

* "/": ["user"],
* "/project": ["project"],
* "/project/{id}" : ["project.commits"]
* "/project/{id}/lineage" : ["project.graph"]

If we are in `/project` we need to re-fetch updates for "user" and "project", but we can safely ignore "project.commits" and "project.graph". We still want to know that something changed for "project.commits" so that the next time we will go to `/project/{id}` we know we will need to re-fetch them. We need to handle only these 3 possibilities:

* I need the updated data: set `fetching=true` and start fetching them, update  `fetched` timestamp when I get the data and set back `fetching=false`
* I don't need the data but I already have them: set `fetched=null` to invalidate them.
* I don't need nor have the data: do nothing

This way we can re-fetch what we need and the UI always know the status by combining the 2 metadata variables.
It's not easy to implement this but it would lead to a realtime UI with a coherent way to save and update data. Here are the main difficulties I found and my view on it. Feel free to reply an add other points.

*TOPICS*
* Implementing the WebSocket backend may not be trivial for all the backend parts, especially the ones without a native hook/events based implementation: true, but we can still create a single centralyzed backend poller to check them and serve all the users. In the worst case we can decide to not provide updates for all topics and let the UI implement a polling strategy based on the timestamp only for those. This requires an extra metadata variable back-end provided.
* WebSockets may lead to non trivial issues with authentication/firewalls/others due to the custom WS protocol: true, we can probably use Server Sent Events that are based on the HTTP protocoll and simplify our life. We don't really need to send data through WebSockets so we shouldn't suffer the most important downside. We can discuss this or try 2 different pilot implementations.
* Multi level refreshable objects (project --> project.commits) is not easy to maintain: right, we should aim to keep almost everything at the 1st level, making every topic independent. I think 2nd level is useful to track dependencies (commits doesn't make sense if I change the project) but we can discuss alternative strategies to address this.
* A single Redux store may become huge: for very big project it may be a problem, but we can probably address this later when we really need it. For most of the cases we can probably safely store in redux all the backend data and the relevant shared data and delegate to react state the local data like the current dropdown selection or the current input text. Another very usefult strategy to pursue is to get only the data we need, not everything returned by the default API implementation. In this case GraphQL may be our friend.
* It requires a huge effert to modify all the UI now along with the new WebSocket backend: right, but with this approach we don't need to do everything in one big step, we can gradually adapt the UI.

**Comment by lorenzo-cavazzi** [comment]
There are many discussion topics, I start with the main difficulties I found and my view on it. Feel free to reply an add other points.

* Implementing the WebSocket backend may not be trivial for all the backend parts, especially the ones without a native hook/events based implementation: true, but we can still create a single centralized backend poller to check them and serve all the users. In the worst case, we can decide to not provide updates for all topics and let the UI implement a polling strategy based on the timestamp only for those. This requires an extra metadata variable back-end provided.
* WebSockets may lead to non-trivial issues with authentication/firewalls/others due to the custom WS protocol: true, we can probably use Server-Sent Events that are based on the HTTP protocol and simplify our life. We don't really need to send data through WebSockets so we shouldn't suffer the most important downside. We can discuss this or try 2 different pilot implementations.
* Multi-level refreshable objects (project --> project.commits) is not easy to maintain: right, we should aim to keep almost everything at the 1st level, making every topic independent. I think the 2nd level is useful to track dependencies (commits doesn't make sense if I change the project) but we can discuss alternative strategies to address this.
* A single Redux store may become huge: for a very big project it may be a problem, but we can probably address this later when we really need it. For most of the cases, we can probably safely store in redux all the backend data and the relevant shared data and delegate to react state the local data like the current dropdown selection or the current input text. Another very useful strategy to pursue is to get only the data we need, not everything returned by the default API implementation. In this case, GraphQL may be our friend.
* It requires a huge effort to modify all the UI now along with the new WebSocket backend: right, but with this approach we don't need to do everything in one big step, we can gradually adapt the UI.

**Comment by lorenzo-cavazzi** [comment]
> * WebSockets may lead to non-trivial issues with authentication/firewalls/others due to the custom WS protocol: true, we can probably use Server-Sent Events [...]

On second thought, this may not be possible, I do need WebSockets because I want to:
* subscribe to specific topics: I don't want notifications for every project but only for the one I am visualizing
* unsubscribe to topics: only WS makes the backend aware of the client status, I don't want to keep notifying disconnect users nor to keep providing not-useful-anymore information to connected users

This means that changing page may imply providing feedback to the backend (e.g. I don't need update on project 95 anymore, but only 106), as well as receiving information (e.g. now I know my `project.graph` topic is out of date but I don't need to refresh it. Don't provide me any more information about that)
