### ISSUE TITLE
🔶 Rework the project status page

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2315]
Currently, the project status page is partially broken and it seems to be confusing for the users.

### Issues

**First, give a look to the next section!**
It's good to keep track of the current issues, but we might want to overhaul the page completely.

* After finishing an update, in some cases the Template section still shows "Updating...".
  Here is an example to fork and update to reproduce the problem: https://dev.renku.ch/projects/renku-ui-tests/renku-project-v8
  ![Image](https://user-images.githubusercontent.com/43481553/213181074-5f5d13c4-6cb1-4494-a4d5-ff87db09a15e.png)
* After clicking on the "Update" button, we should show an "Updating..." message, but we occasionally get different results
  ![Image](https://user-images.githubusercontent.com/43481553/213181473-3fca47f8-d0bb-42ea-9368-60f863ea0f05.png)
* ...On the same topic, we occasionally show the "project is currently being modified". We should *not* show that in this case (i.e. don't invoke the `GET renku/project.lock_status` API just after initiating the update and until it's done)
  ![Image](https://user-images.githubusercontent.com/43481553/213181818-92172d0e-cfa6-435c-82d0-07632895a7e2.png)
* dev only: https://github.com/SwissDataScienceCenter/renku-ui/issues/2135

### User complaints and possible solution:

* It's unclear what each section does (why update the template? the renku version? what are the benefits and/or new features?)
  * We could merge the sections together, include a link to a documentation page explaining what versions and templates do, and potentially add a link to the renku-python changelog (if easy to identify/map).
* KG indexing is now important. The info there is confusing:
  * We should include a link to a documentation page explaining what is the KG indexing (the page should already exist)
  * Keep the warning when non-indexed (this case should be very rare in production), but add more info about the events when indexing (we have them now in the status page) and when indexed (status) and consider showing the errors.
  * :bulb: we might show a cog spinning while KG is processing; hovering over it should show the reason (E.G: "processing dataset metadata", "processing workflow metadata")

**Comment by ciyer** [comment]
Some history behind the current status page is probably helpful. Here are links to previous work on this question:

| Issue   |    PR     |
|--------|-------|
| #942   | #975   |
| #1026 | #1068 |
| #1233 | #1422 |
| #1651 | #1659 |

Especially #1233 has a lot of information on the various states and migration possibilities.

I think ideal goal would be to be able to present the user just a few choices and the information necessary to make decisions:
* Your project is up-to-date, everything is good
* There is a new version available, you might want to upgrade, and here is information about what is contained in the upgrades
* Your project is no longer supported, you need to upgrade for it to work, and here is information about what these changes mean and anything you need to adapt to

But presenting the user such clear and simple choices was not easy in the past because:

1. There are three different pieces that might need to be upgraded: renku metadata version, renku version in Dockerfile, project template version
2. Each of these pieces can be upgraded individually 
3. Some of these do not follow semantic versioning practices
4. There is no way to get links to release notes or change logs for the components

It is possible that there have been improvements to these issues since our last look at the project status. I think the first step towards designing an improvement to this very confusing page is to see if the prerequisites to making it simpler have been fulfilled and focus on those before adapting the UI.

**Comment by lorenzo-cavazzi** [comment]
Another info to show is whether all is good or not with the metadata.
The scope of this issue is getting bigger.

Here is a ShapeUp document on the topic: https://www.notion.so/Simplify-project-status-view-25346cf78fd74c4aab54165748ef966d
