### ISSUE TITLE
Provide better feedback when stopping a session

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2359]
## Motivation

We display a generic message when a user tries to stop a session, but we can now check for unsaved work on sessions and verify whether the repository is dirty/non-synced.

![image](https://user-images.githubusercontent.com/43481553/217049656-a54c5fb6-2f14-4e1f-9141-41341ac25b61.png)

## Proposal

We should invoke the sidecar API to verify the repo status and personalize the message to clarify whether there is unsaved content.
This would be a simpler solution than #2118

**Comment by pameladelgado** [comment]
This is a great suggestion !

I would just show this when there are no changes to be saved and I would follow the format other software does when closing something with unsaved work.

* a prompt with a message along the lines of:
`Your changes have not been pushed, do you want to discard them, save them in an autosaved branch or go back to the session?`
* give three options of the style: `Cancel | Discard | Autosave`

As a user I see two motivations for this feature:
1. some work is not intended to be ever saved and the changes are saved in the autobranch and users have to clean that manually, and make attention to not start sessions from the autosaved branch.
2. unexperienced users might not be aware that they had to [commit+]push their changes in git so that they do not lose their work, or they may just forget to do so.

**Comment by lorenzo-cavazzi** [comment]
Session were completely reworked and now it's possible to keep unsaved code or trash it when stopping/pausing the session
