### ISSUE TITLE
Change meta title on renku projects detail page, so url text will be specific

### ISSUE THREAD

**Issue by sabinem** [SwissDataScienceCenter/renku-ui#2381]
When I copy a link for a project, such as  https://renkulab.io/projects/christian.ruiz/statbot-swiss and and include it in a webpage such as confluence, I always just get as text: "Reproducible Data Science | Open Research | Renku". What I would like to get instead, would be a more specific text, that describes my project such as "Statbot-Swiss | Renku". I don't mind the exact text but I would really like it to be specific.

## Motivation

Copying a link of a project and integrating that link somewhere else is a frequent task. It would be nice if the link text would hint back to the project by being specific for the project.

## Proposal

Make the meta information on the page html more specific: see here for example for the meta data taken from: https://renkulab.io/projects/christian.ruiz/statbot-swiss

```
<meta property="og:title" content="Reproducible Data Science | Open Research | Renku">
```

**Comment by ciyer** [comment]
This is a great idea, but it does not look like it is possible to implement at the moment. 

RenkuLab uses the title that you see as the initial title, and then dynamically updates it to include project information, as you see in the screenshot below:

![Image](https://user-images.githubusercontent.com/1196411/225303341-7e4d39ed-4000-4b57-a429-6083c36bf120.png)

So, if someone navigates to the page in the browser, they see a title that reflects information from the project.

It looks like Confluence fetches the page to generate a title for the link, but it does not execute the JavaScript on the page, so it does not notice that the title is updated (I tried this with the `og:title` tag as well, but had the same issues).

To get the behavior you want, we will need to switch to generating at least the page `<head>` statically, rather than updating it dynamically after the initial page load. This would be quite a big structural change for the UI.

**Comment by ciyer** [comment]
In the meantime, as a workaround, it should be possible to update the link text to be more description. E.g., here in Confluence.



![Image](https://user-images.githubusercontent.com/1196411/225315666-09e550d4-13f5-46fc-8184-cc69fbff5024.png)

**Comment by ciyer** [comment]
Closing for the time being, since the prerequisite for doing this is not currently planned as a priority.
