### ISSUE TITLE
Get project description from KG/core, maintain using core

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2438]
From #2337:

- Description: this is already added at creation time through renku-core. We should:
  - use the `POST /renku/project.edit` endpoint to edit the project `description` also from the project settings page ([API reference](https://dev.renku.ch/swagger/#/project/post_renku_project_edit))
  - verify how quickly that information is updated on KG (do we get the new description if we invoke the KG project API immediately after modifying it? how long does it take re-indexing in this specific case?)
  - If that's slow, verify using the renku-core API to fetch that property ([API reference](https://dev.renku.ch/swagger/#/project/post_renku_project_show))
  - 
- Other properties: do they come from the KG or are those taken directly from GitLab? In the second case, we can consume them right away and start phasing out GitLab for that... Verify with KG team this info, and create follow-up issue where necessary

**Comment by lorenzo-cavazzi** [comment]
A little additional background:
- We initially used the `description` field from GitLab, then we _partially_ switched to storing the same data in the project's metadata. We use that when creating the project, but we also need to read/edit properly everywhere else in the UI.
- We can edit the field using renku-core (see initial post for API references), and read it through KG or core. Ideally, we should read using KG, and edit using core. We might consider using core for both writing _and reading_ if we notice that, after editing, KG shows an outdated value for too long (a few seconds? We should test it and decide on the most reasonable solution).

The description is used:
- On the dashboard and search page: no changes are needed on our side since all data comes from KG -- double check it's working fine, and keep in mind there might be a little delay in getting the up-to-date response.
- On the project title section: we must switch from the (currently used) GitLab description to the KG (or core) description.
- On the project settings section: same as above, and the edit should use the renku-core APIs instead of the GitLab API.
