### ISSUE TITLE
Project visibility button

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku-ui#2515]
## Motivation
Some users want to change the visibility (private, public, internal) of their projects. Currently, this can be only done through the Gitlab settings. It is not intuitive how to do it, if you are not an experienced user. 
![Screenshot 2023-05-11 at 11 07 03](https://github.com/SwissDataScienceCenter/renku-ui/assets/127967525/cd77a390-69bb-4746-8f39-0dc0668a7d38)
View of Renku Project/Settings page

![screenshot_2023-05-11_at_11 06 17_720](https://github.com/SwissDataScienceCenter/renku-ui/assets/127967525/4cd9cccc-7eb4-499d-81b2-ae9090221836)
View of Gitlab Project/Settings page

## Proposal

There are mainly two options:
- Create a button in the Project page / Settings that allows the user to change the visibility of the project (this may have some corner cases that need to be tackled).
- Create a button that redirects the user to the Gitlab settings project page within the Renku Project page/ Settings and give indications to the user on how to do the change (and include it in the documentation page).

**Comment by jdupre81** [comment]
**Forked project** - change visibility

https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/c4b382bd-9297-4f30-b277-774774f800ab

**Own project** - change visibility

https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/4a3c3a9b-b6a9-4926-b699-730b30149196

**Comment by jdupre81** [comment]
as discussed last week, here is the design for the use case:
**Change visibility of my own project + Message on a Confirmation box**
[Figma prototype ](https://www.figma.com/proto/8yrdRbT2CuKYeUlFqNKaqe/Project-visibility-button%232515?page-id=307%3A3412&type=design&node-id=307-3684&viewport=144%2C-54%2C0.16&t=kEkvzkuznxCobBpk-1&scaling=min-zoom&starting-point-node-id=307%3A3417&mode=design)

https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/980a464c-b16e-4a16-8560-e8a47607f2e3

**Comment by lorenzo-cavazzi** [comment]
A few details:
- For the visibilities, re-use the same text/description we have in the "New project" page (mind they are swapped in the prototype above)
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/bce72fa5-43b2-4190-b538-257c6921a49f)
- Do not allow changing visibilities if the project is forked because it's probably going to fail
- If the project is part of a group, check the visibility restrictions: E.G. if the group is internal, users can pick only internal and private, but not public.
- Use the tooltip to explain why users cannot change visibilities in those cases ("Cannot change visibility on forked projects. Please check our documentation" or "This project is inside a private group. Visibility cannon be more permissive then the group one."). No need to show a tooltip when there is nothing relevant to explain.
- Keep in mind changing visibility might be restricted for other reasons. Errors will happen :unamused: . We should keep this in mind for the confirmation modal: when the users confirm the visibility change, we need to wait until it's done and show a green confirmation when all is good, or a red error when something goes wrong with the GitLab message.
