### ISSUE TITLE
Notify users that settings changes only affect main branch

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2641]
There are many things that the user can do in the UI that result in a commit in their repo. A lot of these are related to project setting changes where the request is handed over to the core service and then a commit is made in the repo.

If I am not mistaken these commits are only done on the default branch (i.e. main or master) but not on any other.

So we should either have a message/warning that is always there to say this. Or we should show something when a user is updating a setting but we see they have other branches in the project.

**Comment by olevski** [comment]
This is one such example when it comes to updates:

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/16360283/886e653f-ac9c-4e2d-81f1-7cbc73694230)


I confirmed that in a project with multiple branches only the main branch is updated but there is no warning/notification that the other branches are unchanged.

**Comment by olevski** [comment]
Another component is this:

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/16360283/aadaef83-16e3-412f-b68d-f98a7a1ac05f)

**Comment by lorenzo-cavazzi** [comment]
The UI currently supports interacting with non-default branches only when starting sessions.
I agree allowing users to select a different branch would be great. That has been discussed, and we started a ShapeUp project (currently paused since it's not the most urgent thing).
I feel that's the right way to go; I would be very surprised if users expect changes from the UI to apply to _all_ branches of a project. Adding a notification to specify that might add unnecessary noise.

**Comment by lorenzo-cavazzi** [comment]
Hello @olevski 
As discussed offline, the UI doesn't support branches at the moment, except for the session pages.
We want to expand support to branches but we should develop a common solution instead of having multiple issues for different pages/components.
Please for now refer to [this ShapeUp document](https://www.notion.so/Branch-based-Project-Explorer-90a0fcbe1b254e3d8121c0c7e9831cd6) for initial discussions/ideas; you are very welcome to contribute there.
