### ISSUE TITLE
The UI for adding a dataset should mention that the dataset will be added to the main branch only

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2667]
It would be nice if the following is mentioned:
- the branch name to which the dataset will be added
- a link to the CLI or docs and a mention that if the user wants to add the dataset to another branch they can do so only through the UI

Another thing is I am not sure what happens if the main branch is protected? I guess then adding the dataset creation will fail. But perhaps we should check for this and immediately inform the user.

Here is the screen I am talking about:

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/16360283/9c843e44-c9bf-4f34-b00c-8a8f217426b8)

**Comment by lorenzo-cavazzi** [comment]
Hello @olevski 
when the branch is protected we create another branch and inform the user through the UI.

As discussed offline, the UI doesn't support branches at the moment, except for the session pages.
We want to expand support to branches but we should develop a common solution instead of having multiple issues for different pages/components.
Please for now refer to [this ShapeUp document](https://www.notion.so/Branch-based-Project-Explorer-90a0fcbe1b254e3d8121c0c7e9831cd6) for initial discussions/ideas; you are very welcome to contribute there.
