### ISSUE TITLE
The UI for listing datasets should mention the branch the dataset resides on

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2668]
Currently the UI only shows datasets only from the main branch.

But this is not mentioned anywhere in the UI.

We can correct this in 2 ways:
- mention the branch in the dataset cards
- mention this in the page that lists the datasets

I like adding "branch" as part of the dataset card. But I leave this decision up to you. If this is added to the card then it is clear where the dataset is from wherever the card is displayed. If we add text only to the dataset list page then we will probably have other cases where the datasets are displayed in other pages but the branch explanation is missing.

**Comment by lorenzo-cavazzi** [comment]
Hello @olevski 
As discussed offline, the UI doesn't support branches at the moment, except for the session pages.
We want to expand support to branches but we should develop a common solution instead of having multiple issues for different pages/components.
Please for now refer to [this ShapeUp document](https://www.notion.so/Branch-based-Project-Explorer-90a0fcbe1b254e3d8121c0c7e9831cd6) for initial discussions/ideas; you are very welcome to contribute there.
