### ISSUE TITLE
Re-organize the top and bottom bars on the landing page for anonymous users

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2681]
## Motivation

* The search button is too hidden on the anonymous landing page (some users have difficulties exploring the projects/datasets) and makes it difficult to explore content.
* We have a bunch of links on the top bar pointing to social media that we don't keep updated. We might use the space for more relevant pages.

## Proposal

- Move the Search button to a more prominent position.
- Re-arrange the links on the top bar and bottom bar, potentially moving social icons to its own section.
- Logged users: focus the search input box immediately when reaching the search page (UI only)

**Comment by jdupre81** [comment]
**Analysis** of the current state of the landing page -> top nav bar & first section: 
	◦	Unused links/pages: see issue https://github.com/SwissDataScienceCenter/renku-ui/issues/2685 
	◦	`Medium, Youtube, Twitter`, `Sessions page` (from anonymous user) ? Do we want to keep them or would be better to take them out? 
	◦	`Learn more` button on first section -> is an anker point to the next section. Not really useful, in my opinion.
	◦	`Learn more` button on the last section -> redirects to the documentation.

**Comment by jdupre81** [comment]
**Search bar design proposal**

_Please note that I have introduce 3 new buttons on the first section `Sign up` , `Get Started` ,  `Learn more`_

Search bar on the top nav bar middle
![Desktop - Design proposal 1](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/08b731af-a0aa-46f8-b077-684465212b43)

**On the content section:**
• center middle
![Desktop - Design proposal 4](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/f5751d5b-045a-422c-9481-996aba3499ff)

• left aligned top of the section
![Desktop - Design proposal 2](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/2ae9b06f-c39c-4fca-a846-b8a43b60dc8a)

• left aligned middle of the section
![Desktop - Design proposal 3](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/622396b7-819c-4d42-a7ac-ee14ea251d89)

**Mobile** 
![Mobile 1](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/3c30dd25-7381-4570-a695-dc15f00dac5c)

![Mobile 3](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/81c17f16-5bb2-4091-814f-1400c67775f9)

Please note that for all design proposals I have not consider the hamburger because of the issue [#2685](https://github.com/SwissDataScienceCenter/renku-ui/issues/2685)

Looking forward to discuss all details next week on our UI POD meeting

**Comment by jdupre81** [comment]
User Journey Map for this case
![User Journey Map - Search bar on landing page](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/1320f4ae-d9b7-4f5c-827a-b8bdf8352748)

**Comment by lorenzo-cavazzi** [comment]
I personally like this solution (:warning: the "sessions" page link seems to be gone tho)

**center middle**
![Desktop - Design proposal 4](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/f5751d5b-045a-422c-9481-996aba3499ff)

**Comment by jdupre81** [comment]
> I personally like this solution (⚠️ the "sessions" page link seems to be gone tho)
> 
> **center middle** ![Desktop - Design proposal 4](https://user-images.githubusercontent.com/117274853/255161931-f5751d5b-045a-422c-9481-996aba3499ff.jpg)

Cool, thanks for voting .. hehe - Let's see what others opinion are !

**Comment by jdupre81** [comment]
Here is another design proposal

Considering that the we want to keep the sessions page it would be important to reorganise some of the icons from the top nav bar, in order to simplify the navigation for the user.

In the following design  I have put all the social media icons under the hamburger. This way, the most important icons `Call to action buttons`, have more presence and visibility. 

looking forward to discuss all designs on our UI POD meeting.

https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/18d1f490-25fa-4a1e-a01c-30c3cc38a93a

**Comment by lorenzo-cavazzi** [comment]
Looks good!

We should eliminate the second GitHub link -- we have one in both the Help and the hamburger menu. Also, in the proposal, there is a new Documentation link. We have it in "Renku Docs" in the help menu too.

Should we have a single menu instead and leave the question mark as a link to the Help page?

**Comment by jdupre81** [comment]
Final design. - [Figma link](https://www.figma.com/file/qFKV4jeWVr0v6y9XB0bmQO/Make-the-search-button-more-immediate-%232681?type=design&node-id=358%3A3472&mode=design&t=54yP7xhG6NN6H0jM-1)

![final design](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/cbae9b53-dd3e-4310-95fa-26405bd65dcd)

**Comment by jdupre81** [comment]
<img width="1012" alt="Screenshot 2023-08-11 at 10 05 07" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/88dcaeea-4577-4065-b781-2a94d46d4fce">
