### ISSUE TITLE
Forking private projects

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2830]
I have reports from a class where the students are added as Reporter members to a private group. The idea is that they should fork one of the private projects in this group and then work on the fork.

Here is what they are seeing:

Teaching assistant:
> Sometimes students cannot fork the session. It seems to happen to students that just have been added to the student group.
> Camille found a workaround that is a bit strange: he upgrades the student membership to "developer" inside the student group. Then the student is able to fork the session. Once this is done, the membership can be downgraded and the student can fork other sessions.
> I found this workaround strange because the student group membership in the sessions repos is always "reporter", and some students (including my dummy student account) never had to be upgraded from "reporter" to "developer" to fork the sessions.

Instructor:
>  forking from the UI is often not possible as the button is greyed out, BUT it’s possible when going under sessions, and there there is a message suggesting to fork as the user does not have permissions

**Comment by lorenzo-cavazzi** [comment]
Thank you for reporting this. It's not totally clear to me what's the issue since "forking a session" is not really a thing.

Generally speaking, users need to be developers to create a project in a namespace, reporter is not enough. That's not required to start a session. So the following feedback is not surprising and it doesn't sound like a workaround to me

> he upgrades the student membership to "developer" inside the student group. Then the student is able to fork the session. Once this is done, the membership can be downgraded and the student can fork other sessions.

I suspect those users fork projects in a group namespace as developers, and then they later push commits also as reporters. That setup sounds far from ideal since other students could push code in their repos. If they use that to keep project visible to the whole group, perhaps having projects in their own namespace and sharing guest permissions to the groups is a better solution.

**Comment by lorenzo-cavazzi** [comment]
Closing this, but please feel free to contact me directly; happy to talk about this point.
