### ISSUE TITLE
add session status to favicon of session page

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-ui#2905]
it'd be it'd be nice if we could decorate the favicon on session tabs with the status of the session, similar to github's icon on PR tabs
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/664486/40c05b94-18ce-4521-ac61-f203a419da1e)
green play button for running, yellow hourglass for pending, maybe red x for failed.

This would enable users to see at a glance when their session is ready without switching to the tab to check. Especially useful for sessions that take longer to start

**Comment by lorenzo-cavazzi** [comment]
I like the idea!
I guess we never really stay on the session page in case of errors since we don't have much to show, so the red X might not be necessary. But the green play button and the yellow hourglass (or perhaps just the dot as GitHub does since the space is really small for an hourglass) are both neat ideas :100:
