### ISSUE TITLE
Cannot stop/restart a failed notebook server

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-ui#361]
How to reproduce:
- Create a docker image that fails on start, e.g. exit 1 in entrypoint/cmd
- Try to start the notebook server which fails, it cannot be stopped and cannot be restarted.

**Comment by ableuler** [comment]
@erbou Does the server not appear on the list of notebook servers or does it refuse to dies when you try to stop it? Either way, I think this is not an issue of the UI but of the Notebook service not having control over these "zombie"-pods. What do you think @rokroskar?

**Comment by rokroskar** [comment]
Oops it seems I missed this one for some time. One possible way of improving this would be that the notebook service would check the state of the server when receiving a `DELETE`. If the server is in some failed state, we should remove it using the kubernetes API instead of sending a `DELETE` to jupyterhub. *However* in that case, it will still take some `timeout` number of seconds before jupyterhub removes it from the list of known/running servers.

Which brings me to another point - if a notebook launch failed on start, why would it succeed a second time? Usually that's because something is wrong with the image. In that case, a fix requires a change to the `Dockerfile` which means a new commit which means that you can launch a new server. Or do you have a different scenario in mind @erbou?
