### ISSUE TITLE
"View project in GitLab" button is broken

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#384]
On both deployments, renkulab and limited, the button does not link to GitLab, instead the user is brought back to the UI.

**Comment by rokroskar** [comment]
Potentially related to #370 -- I think we're seeing some improperly handled token expirations.

**Comment by lorenzo-cavazzi** [comment]
@ableuler I am trying to reproduce this on renkulab. The button "View Porject in GitLab" seems to bring back to the UI only when we are viewing a non-existing (or private) project, otherwise it works fine for me
[#351 public project --> working](https://renkulab.io/projects/351/)
[#352 N/A project --> back to UI](https://renkulab.io/projects/352/)

In the latest renku-ui releases the button is not available if the project is not public.

**Comment by lorenzo-cavazzi** [comment]
I have not been able to reproduce this issue except in the case above. If possible please provide some more info.

**Comment by ciyer** [comment]
I believe this duplicates #365. Closing.
