### ISSUE TITLE
Save lineage graph from the browser and permalink

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#405]
It would be great to be able to have a download button to save the lineage image.

https://renkulab.io/projects/377/files/lineage/outputs/plot.pdf

![image](https://user-images.githubusercontent.com/4173925/54824107-35aa1100-4caa-11e9-9974-11f405da10b3.png)

A permalink would be very helpful too.

**Comment by lorenzo-cavazzi** [comment]
The Lineage feature won't be further expanded since it won't be part of the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
