### ISSUE TITLE
Clean up interactive environment launch page

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#482]
# Description

The page to launch interactive environments should be cleaned up. The form fields should have a more logical ordering. Any options that are not relevant should be hidden (e.g., if there are no GPUs available, do not show the GPU input; only show the Server URLs that the project has defined)

# Mock Up

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1196411/58937620-3dd70000-8773-11e9-95e9-2f5339629e22.png">

**Comment by lorenzo-cavazzi** [comment]
According to #568 we will use `Interactive environment` instead of `Activity` as the tab text. #599 also defines a new tab for collaboration, so "merge requests" will be in that tab.

This leaves 2 entries on the left menu, 1 for the list of running notebooks and the other for starting a new one. After speaking with @ciyer , we agree to define these 2 pages as `Running` and `New`  -- any other suggestion is welcome :slightly_frowning_face:

**Comment by lorenzo-cavazzi** [comment]
The labeling and the order of the listed properties come from the API `notebooks/server_options`, that in turn reads them from a file stored in `/etc/renku-notebooks/server_options.json` on the server -- but I failed to identify who is loading the file.
Anyway, ordering and wording should be changed there. I also think it doesn't make sense to return useless parameters (e.g. 0/0 gpus), these should probably be removed from the file.

I like the multiple selection buttons in the mockup.
The whole page is changed quite a lot and now there are other dropdown menus (branches, commits). I think those should stay as the are.

![Screenshot from 2019-09-16 16-17-23](https://user-images.githubusercontent.com/43481553/64965809-f269dd00-d89d-11e9-8f7e-28cdc374f037.png)
