### ISSUE TITLE
Navigate through commits in the knowledge graph

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#543]
The user should be able to navigate the graph through a list of relevant commits. 

(A list of relevant commits should be provided to the user in chronological order along with a back and forward navigation buttons so the user can see the progress that the lineage did or choose a specific commit to see the state of the graph at that point).

The user should also be able to choose for a specific node, a certain commit from a dropdown of commits and be redirected there

We should discuss if the file view/explorer should be consistent with the current commit chosen (In this case, the file shown and also the files tree should also display the state of the file/repository at that commit) Related with #544

**Comment by lorenzo-cavazzi** [comment]
The Lineage feature won't be further expanded since it won't be part of the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
