### ISSUE TITLE
Display extra information about the nodes and edges

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#545]
After [92](https://github.com/swissdatasciencecenter/renku-graph/issues/92)  is closed there will be extra information coming from the backend and we should choose relevan information and display it.

It could be in a tooltip, using different colors for nodes, etc.

We should also stop using the "blob" and "commit" to style the graph and choose some other relevant way of making a diasctintion between nodes.

**Comment by lorenzo-cavazzi** [comment]
The Lineage feature won't be further expanded since it won't be part of the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
