### ISSUE TITLE
Allow user to change the graph orientation

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#549]
For some graphs, it's easier to visualize it when the direction goes from right to left instead of top to bottom. There is an option in D3-dagre to change this (rankdir).

Example:

From:
![image](https://user-images.githubusercontent.com/42647877/61794016-95632500-ae20-11e9-9921-9a4c8dea4379.png)

To:
![image](https://user-images.githubusercontent.com/42647877/61793981-79f81a00-ae20-11e9-89e9-717c8bd0142e.png)

**Comment by lorenzo-cavazzi** [comment]
The Lineage feature won't be further expanded since it won't be part of the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
