### ISSUE TITLE
No reference to project name in Jupyter notebook

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#584]
For example:

https://renkulab.io/projects/761/

![image](https://user-images.githubusercontent.com/4173925/63918066-3eaec380-ca3c-11e9-9c74-c74b7e1e23f8.png)

In the notebook, I can't seem to find any reference to the project name, neither in the URL (https://renkulab.io/jupyterhub/user/cchoirat/7ba04c982d5dd104/lab?) nor in the UI
![image](https://user-images.githubusercontent.com/4173925/63918161-7289e900-ca3c-11e9-8285-ee965fadb6b1.png)

**Comment by ciyer** [comment]
Here are a two solutions I can think of:

- #167 changed the UI URLs to include project home and project name. We could do something similar in the notebook server
- We could display the information in the Renku Plugin for JupyterLab/R-Studio 

Do you have preference?

**Comment by cchoirat** [comment]
Strong preference for 1: #167

**Comment by rokroskar** [comment]
How can we easily do 1?

**Comment by lorenzo-cavazzi** [comment]
True, solution 1 is not trivial (for now) and solution 2 seems to be the only reliable way to show consistent information (long names or special chars can't be handled nicely in the URL).
On the other hand, we can easily change the url to something more meaningful. It won't be a perfect solution but it may already be enough to convey information that is useful in most cases.

At the moment the notebook name is a 16 chars string hash and, according to the JupyterHub spawners code, we could go up to 63 chars without problems.
The simplest solution would be adding the first 46 chars of the project name to the server name (see below an example of a project named `zurich-bikes-tutorial`).
Keep in mind that the name would be abbreviated and escaped, but I guess it is fine. I think it shouldn't contain information about the namespace because most of the time it wouldn't add extra information `myUserName/myUserName-projectName-hash/` or otherwise be only more confusing `myUserName/anotherUserName-projectName-hash/`

![Screenshot from 2019-09-11 16-37-56](https://user-images.githubusercontent.com/43481553/64706942-9294c000-d4b2-11e9-9771-9225963cc5ee.png)

**Comment by lorenzo-cavazzi** [comment]
@cchoirat please let me know if the proposed solution is acceptable :slightly_smiling_face:

**Comment by cchoirat** [comment]
Thanks @lorenzo-cavazzi, that will be a super useful change!
