### ISSUE TITLE
Automatically load commits after changing the branch in notebook server launch panel

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#588]
A small issue that I just came across:

After changing the branch in the `Start new JupyterLab server` form, the commits dropdown remains empty until I manually refresh the commits (see screenshot). Changing the branch should automatically trigger loading the available commits. 

![image](https://user-images.githubusercontent.com/13014091/64021835-2373af00-cb35-11e9-8498-20a58c8a8aa3.png)

**Comment by lorenzo-cavazzi** [comment]
It's not a bug, it's a feature! :sweat_smile:

The default behavior is to re-fetch the commits as soon as you select the new branch -- you should see it in the network pane in the debug tools. If the same commit is available in the newly selected branch, it is automatically selected, otherwise you have to select it manually. The idea is to make the user aware that the same commit is not available in the selected branch.
Since you opened an issue, it's probably not that obvious. We can change the behavior -- e.g. always select the last available commit, but I am not sure that would be better...

P.S. manually refreshing the commit list results in automatically selecting the last one because that is the default behavior when nothing was previously selected.

**Comment by rokroskar** [comment]
My expectation when I select the branch is that I will see the commits of that branch starting with the most recent one - I am not expecting to see the same commit with a different branch name. In fact I expect a different branch to _not_ have the same commits, that's why I'm selecting it in the first place. I was also confused by the current behavior I suppose :)

**Comment by ableuler** [comment]
Ok, I understand. My expectation would be that changing the branch loads the available commits in that branch and pre-selects the most recent commit of the selected branch.

**Comment by lorenzo-cavazzi** [comment]
Ok, then it seems reasonable to always select the last commit when a new branch is chosen. I'll go for that solution.
