### ISSUE TITLE
Misleading image availability information during notebook launch

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#590]
Merging #575 has introduced very useful information about the availability of a docker image when trying to launch a new notebook server. For most of the use-cases, this information is correct. However, as this information is gathered from the pipelines API and not from the registry API, this information is wrong for all cases where no pipeline has ever been run.

After forking a project, an image build is only triggered for the latest commit of the master branch. When choosing an older commit or a different branch, the UI will tell the user that the corresponding image is ready, but silently fall back on the default image when launching a notebook, leading to very confusing results.

A better solution would be to check the relatively recently introduced gitlab container registry API for the existence of the right image. I am not sure if this has been tried already? Otherwise, there must be a way to alert the user in cases where we don't know if the image is available or not.

**Comment by lorenzo-cavazzi** [comment]
It seems that the bug is in how the UI handles the response from the GitLab pipeline API when no pipeline is returned. It should display information about the missing pipeline. I'll check into this.

Btw we didn't check the new container registry API: Sooner or later we will not create an image for every commit -- the new API seems to be even more useful in that case, thanks for mentioning it :slightly_smiling_face:

**Comment by lorenzo-cavazzi** [comment]
Let me recap the current status more in detail.

* The UI shows a misleading message when no pipelines are found for a commit under specific conditions. This is clearly a bug and it should be easy to fix.
* Forking the project doesn't build the image for old commits. It doesn't make sense to automatically do that but currently there is no easy way for a user to start interactive environments from old commits with the proper image. Since the idea is to overhaul the current Docker image workflow, we should probably move further discussions about this to the new proposal SwissDataScienceCenter/renku#646 (or to #589 if it's more focused on branches)
* I have checked the container registry API. It allows verifying *for sure* if the image is available but any information about the current status (building the image) is bound to the job/pipeline actually building the image, therefore it cannot substitute it. Adding this extra check would be great but it would require polling another resource -- it would be 3 at the same time.
