### ISSUE TITLE
Info about limited permission for "< Maintainer" users

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#611]
Users that are not `Maintainer` for a project have some limitations while using interactive environments (e.g. SwissDataScienceCenter/renku-notebooks#212). It would be good do display an info message to "less than Maintainer" users while starting a new environment.

Other info: we may add a link to this page for extra info about limitations: https://docs.gitlab.com/ce/user/permissions.html
At the moment we only allow >=Developers to start environments but we may want to revise this in the future SwissDataScienceCenter/renku-notebooks#171

**Comment by emmjab** [comment]
Ran into this issue again -- was Developer on a project and had access to the button to launch the notebook, but since I was not Maintainer I didn't have sufficient privileges to *actually* launch, so I got stuck on Pending. We changed my role from Developer to Maintainer, but there were backend issues with the node from having launched before with different permissions, and clicking "launch server" kept sending me back to the "start new server". Pamela then had to restart the node.

**Suggested UI updates**
People with developer role should see the same "unable to launch notebooks without sufficient permissions" messages as the others.

**Comment by lorenzo-cavazzi** [comment]
thanks @emmjab for reporting this. The problem should be fixed by SwissDataScienceCenter/renku-notebooks#212 , but that is not part of a new renku release yet.
Currently, the only environment where the fix is deployed is https://dev.renku.ch/ . If you can re-produce the problem it would be great if you verified that the fix work fine on `dev`, so we don't have to wait longer for a comfirmation.

**Comment by rokroskar** [comment]
I believe this is no longer a problem - please re-open if that is not the case.
