### ISSUE TITLE
Hide fork button or display a message when the user has no rights to fork the project

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#620]
At the moment the fork button is in every project, even if the user doesn't have rights to fork it. 

Gitlab hides the fork button for the users that can't fork the project, we could do this or instead of this we could grey the button and on hoover show a message that says that the user needs more rights.

**Comment by lorenzo-cavazzi** [comment]
On the other hand, Github is showing the button also for anonymous user and it asks to login when the user clicks on it. This behavior is similar to ours. Personally, I prefer the current one.

Anyway, even if we decide to stay with this, we should probably still uniform what happens when clicking on "star".

![Screenshot from 2019-09-16 17-18-04](https://user-images.githubusercontent.com/43481553/64970395-fb5eac80-d8a5-11e9-9e6c-9e186abf42de.png)

**Comment by vfried** [comment]
I see, then we should copy this functionality to the fork button, so it says that you can't login to fork a project as in star.

**Comment by ciyer** [comment]
Just tested. When I try to fork a project and am not logged in, I get taken to the log in page, but am redirected back to the project page without the fork window afterwards.
