### ISSUE TITLE
feature request: display lineage icon on files that have been part of renku run

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#622]
When debugging how renku run is working and generating lineage graphs, or looking at others' projects to see which data and scripts have been run in the project, it would be nice to know which files to click on to view a graph.

One way to do this would be to replace the "file" icons next to those files with the "lineage" icon (that you click to see the lineage displayed for the file). It would be satisfactory to only display these icons for files in `data` and `src`.

<img width="1327" alt="Screenshot 2019-09-18 at 10 53 14" src="https://user-images.githubusercontent.com/1056472/65133294-a84e3c00-da02-11e9-8c30-b8cf90bc5001.png">

**Comment by ciyer** [comment]
This is a good idea. I think it would make the lineage more useful, but we need to see how this can be implemented efficiently.

**Comment by lorenzo-cavazzi** [comment]
The Lineage feature won't be further expanded since it won't be part of the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
