### ISSUE TITLE
Lift issues and merge requests state to root

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#624]
Issues and merge requests components have their own redux stores. This should be lifted up to the top level store.

UPDATE: see next comment for further info

**Comment by lorenzo-cavazzi** [comment]
A few things changed since this issue was created, and now we have collaboration pages (including collaboration, merge requests, issues, and contributions) with heterogeneous ways to store data.
Here is my proposal to move the data to the global redux store, unify the functions into 2 (or even 1) coordinators, and standardize file naming.

### Refactoring
* [ ] /collaboration/lists/CollaborationList.state.js
    * `CollaborationListModel` --> use global redux store, move functions to issuesCoordinator
    * `collaborationListSchema` --> move to RenkuModels.js (either it's own schema or `projectGlobalSchema`)
* [ ] /collaboration/issue/Issue.state.js
    * `reduceState` --> use global redux store, move functions to collaboration coordinator. That requires changes to `Issue.js` as well.
* [ ] /collaboration/merge-request/MergeRequest.container.js
    * `MergeRequestContainer` --> move state to global redux store, move functions to mergerequestsCoordinator
* [ ] /contribution/Contribution.container.js
    * `NewContribution` --> This could stay as local state since the content is volatile. It may still be useful to move it to coordinators to preserve non-submitted code on accidental users click if it's easy.

### Restructuring
An idea is having `issues` and `merge-requests` as sub-folders with dedicated coordinators, and `contributions` without a coordinator. The `collaboration` files will have minimal content.
```
> collaboration
    container.js
    present.js
    test.js
    > issues
      container.js
      state.js (this may be unified in a single collaboration state)
      present.js
      test.js
    > merge-requests
      container.js
      state.js (this may be unified in a single collaboration state)
      present.js
      test.js
    > contributions
      container.js
      present.js
      test.js
```
We can further split `issues` and `merge-requests` to have the listing and the single item separate, but I wouldn't do that for now, it doesn't seem necessary.

### Restyle
Since this requires to refactor and move around quite a few components, it may be easy to tackle at the same time minimal visual changes proposed here #854 (not the whole issue)

**Comment by ciyer** [comment]
Made obsolete by #1330
