### ISSUE TITLE
Replace hardcoded keycloak URL

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#630]
Currently, the `profile` link in the navbar assumes that Keycloak is running under `/auth` which must not always be true. Either we should pass the correct URL into the UI using the chart or the UI should query it from the gateway.

**Comment by lorenzo-cavazzi** [comment]
Personally, I prefer to pass it using the chart because it doesn't add a delay when the UI loads and it is coherent with how we inject the other URLs 

https://github.com/SwissDataScienceCenter/renku-ui/blob/2bdd3b8bae148b061c15d46d7cc433b6e58062c4/helm-chart/renku-ui/templates/deployment.yaml#L30-L40

**Comment by ableuler** [comment]
> Personally, I prefer to pass it using the chart because it doesn't add a delay when the UI loads and it is coherent with how we inject the other URLs

I see your point, but the purist inside me wants to cut down the web of interdependencies in between our services. And this would re-introduce the UI-Keycloak dependency...

**Comment by lorenzo-cavazzi** [comment]
In some ways, UI will always have dependencies (we can't avoid injecting at least the gateway url). It seems more coherent to add another one there instead of adding a delay every time the user loads the renku UI. We won't probably need any other URL since the UI needs only the gateway and the authentication server to work properly, so I wouldn't bother too much about creating too many dependencies between services.

**Comment by ableuler** [comment]
Hmmm, sorry for being a bit stubborn here, but having fought not too long ago to remove this dependency in order to simplify our deployments a bit I would really prefer not introducing it again. However, I see your point that you don't want to slow down the initial page load any further. I see two options: 

1. Don't load the profile URL on UI page load but only when the user clicks the profile in the dropdown. This would add some delay when the user clicks on profile, but this is rather rare anyway. 
2. We create a small user info page in our UI based on the information that we get from the `<keycloak-url>/realms/Renku/protocol/openid-connect/userinfo` endpoint (this endpoint is part of the openid-connect standard) and on this page we offer a button/link to the keycloak account page. Access to the `/userinfo` endpoint goes through the gateway.

**Comment by ciyer** [comment]
The reasons for removing the Keycloak configuration information from the UI config were to reduce the coupling between the UI and the authentication provider and to avoid duplication.

I am against implementing our own user profile page because this will tie the UI closer to the authentication provider. 

I think adding a configuration parameter USER_PROFILE_URL to the UI does not tie the UI to Keycloak. We could instead add an endpoint to the gateway that returns the userProfileUrl, but I don't see a reason to prefer this to adding the USER_PROFILE_URL to the UI config.

**Comment by ableuler** [comment]
> I am against implementing our own user profile page because this will tie the UI closer to the authentication provider.

Not sure -- the openid-connect standard is pretty specific about this endpoint. However, it's not my preferred solution either.

> I think adding a configuration parameter USER_PROFILE_URL to the UI does not tie the UI to Keycloak. We could instead add an endpoint to the gateway that returns the userProfileUrl, but I don't see a reason to prefer this to adding the USER_PROFILE_URL to the UI config.

I would just really like to make our deployments simpler and our `some-deployment-values.yaml` files shorter. Telling the UI about the auth provider just for getting some profile information goes against that. 

Could a redirection on the level of the GW make all of us happy? (`/api/auth/user-profile` --> keycloak user info page)

**Comment by ciyer** [comment]
Yes, that would be fine. The UI would always point to /api/auth/user-profile and the gateway would handle redirecting it to the correct URL.
