### ISSUE TITLE
Display of images specified with relative path in readme files

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#667]
There is no image preview for markdown files like: 

https://renkulab.io/gitlab/bst262-2019/problem1

Image from gitlab:
![image](https://user-images.githubusercontent.com/42647877/68042146-78b57380-fcd2-11e9-90d2-0d05e50106fd.png)

**Comment by ciyer** [comment]
The problem is the path to the image. In the README above, the path is specified as a relative path and doesn't resolve correctly in the Renku UI. Image preview does work for image paths that are fully specified. So that is a workaround, but I agree that it should work the same in Renku as in GitLab.
