### ISSUE TITLE
New projects have undefined creation dates

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#675]
New projects created through the UI do not have correctly set `created` and `updated` fields of `.renku/metadata.yml`. 

See, [this example](https://dev.renku.ch/gitlab/rokroskar/test-a-new-project/blob/master/.renku/metadata.yml).

UI version is `0.7.1`.

**Comment by lorenzo-cavazzi** [comment]
Recently, the templates repository got updated SwissDataScienceCenter/renku-project-template#48 and a new version `0.1.4` has been released. This requires the latest version of the UI to work properly #672 . The version `0.7.1` of the UI doesn't contain it, therefore the templates `0.1.2` (or 0.1.3) should be used https://github.com/SwissDataScienceCenter/renku-ui/blob/a7c227bfa7db42ed0c784ee6bcdf7ed36843177b/helm-chart/renku-ui/values.yaml#L63

The problem may appear on custom namespace deployment due to this setting provided in the values files template https://github.com/SwissDataScienceCenter/sdsc-dev-docs/blob/712b0b964100437b2d22e6c15a65f72c2ead3f2c/dev-deployments/dev.values.yaml.template#L80 that overwrite the value provided by the ui repository

**Comment by rokroskar** [comment]
Would it be possible to check in the UI whether the supplied template version makes sense? If it doesn't, e.g. `version < 0.1.2` then the UI should fail with an error. This will prevent a bad combo from being deployed.

**Comment by lorenzo-cavazzi** [comment]
The UI is already shipping with the correct value, the problem is that the value was overwritten by a custom value passed to `helm upgrade`. It seems a bit counterintuitive to me that the UI checks if the values provided have not been changed -- how should I do that? Either I add other values (they may be overwritten as well) or I had static checks about the version number (then it's easier to just put a static variable somewhere).

The new `template-init` code in python (that will replace this in the UI) already contains extra checks. We may also provide feedback to the user about missing jinja variables expected in the template files so that it's easier to catch these problems.

**Comment by rokroskar** [comment]
yes you're right, it occurred to me after I wrote the comment that doing validation in the service to initialize a project would make the most sense so we can postpone.
