### ISSUE TITLE
feat: show forks / starrers of a project on hover

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#746]
It would be nice if the list (or the first 10 items of it) of forks / starrers of a project would be displayed when hovering the fork- or star count of a project. A click on those numbers could take the user to the corresponding pages on GitLab.

**Comment by rokroskar** [comment]
Related to #765

**Comment by lorenzo-cavazzi** [comment]
For the starrers, it seems that the API `projects/<id>/starrers` doesn't return any value but a `404` response. I am wondering if there is any permission limitation, despite the API docs doesn't say so https://docs.gitlab.com/ee/api/projects.html#list-starrers-of-a-project
I cannot see the starrers in GitLab as well.

For the forks, #768 adds the link to GitLab.
Building the logic for querying and showing that information requires a bit of effort. If we do that, I would suggest we replicate the Gitlab's forks page instead of adding a simple tooltip.

**Comment by rokroskar** [comment]
Personally I don't think that showing forks or starrers in a tooltip is useful - would be better to just do #765 for now.

**Comment by lorenzo-cavazzi** [comment]
I agree. Let's close this and, if #765 doesn't turn out to be enough, we can re-open the issue or discuss a different solution.
