### ISSUE TITLE
feat: show projects for a user

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-ui#750]
When I open a profile of some user and try to see which public projects that person has I'm greeted with this never ending loading circle and information never gets to be displayed.

![image](https://user-images.githubusercontent.com/1253355/73832888-4f444080-4809-11ea-8a96-21d7a82840d6.png)

Expected behavior would be to nicely preview that persons public projects.

**Comment by ciyer** [comment]
Problem: urls of the `projects/[user/group]` do not resolve to anything.

**Comment by lorenzo-cavazzi** [comment]
I like the idea.
Currently, the page shows something because it matches the `/projects/<something>` url, but it's not the user page -- in fact, we don't treat the user as a first-class citizen in the ui.

We may go for 2 ways:
* Just show the list of projects for the target user/group. In this case, I am wondering if it makes sense to simply redirect to the corresponding search page (e.g. https://dev.renku.ch/projects/lorenzo.cavazzi.tech --> 
https://dev.renku.ch/projects/search?q=lorenzo.cavazzi.tech&searchIn=users)
* Create a page similar to gitlab user's page. We can start with the list of projects, but I would put that under `/user/<name>` or `/group/<name>` (E.G. in gitlab, this is a user's page https://dev.renku.ch/gitlab/users/lorenzo.cavazzi.tech)

**Comment by emmjab** [comment]
@cchoirat
