### ISSUE TITLE
feat: pagination change

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#764]
## Motivation

@cchoirat 

## Proposal

Change the pagination from "1|2|3|4|5|Next" to a format that includes total page count, e.g. "Prev|1|2|...|[total pages - 1]|[total pages]|Next"

## Context

current:
![image (1)](https://user-images.githubusercontent.com/1056472/74276840-c6506c00-4d16-11ea-8dd6-c62e7e7af31f.png)

**Comment by lorenzo-cavazzi** [comment]
This happens to be fixed by #1042 but the result is slightly different than the proposed one.
Basically, the solution adds a "go to first" and a "go to last" page buttons.

![Screenshot_20200922_151136](https://user-images.githubusercontent.com/43481553/93898583-a6911580-fcf3-11ea-9c7b-ec139470aaa5.png)
