### ISSUE TITLE
[Environments] Add info about requested resources

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-ui#788]
## Motivation

Users are usually not aware of -or do not remember- how many resources a given environment requested and there is no way of getting this information from the UI.

## Proposal

It would be nice to have one or two columns in the environments page where the amount of requested resources are displayed. This is important also because if the amount of used resources exceeds the request, the environments kernel gets killed.
In combination with https://github.com/SwissDataScienceCenter/renku-jupyter/issues/33 , this would improve a lot the UX related to resource usage imo.

Ideally, the amount of resources needed to run a given project would be saved in a setting, so that when the project is forked the correct amounts are set by default. This can be useful for courses.

**Comment by ciyer** [comment]
This is a great suggestion!

IIRC we looked into this before, but we didn't have access to the information about the environment after it had been launched. If other changes have made this information easy to access, then we can quickly implement this. Otherwise, we will need https://github.com/SwissDataScienceCenter/renku/issues/712 first. 

We will look into it and update the issue.

**Comment by ciyer** [comment]
This is also related to #430.
