### ISSUE TITLE
Project page improvements

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-ui#831]
## Proposal

Project page can use some improvements:

1. In the Project's actions tab `Collaboration` link can go to the very end. 
2. Project overview can show environments as well.
3. Project Setting actually has no setting in it. Information displayed there can be show in the Overview page.

**Comment by ciyer** [comment]
1. I agree, it makes sense to have `Collaboration` before `Settings`
2. Good suggestion -- if there are running environments, they can be shown on a tab in the overview. That would be convenient!
3. I think we should keep the `Settings` page since the project tags and descriptions are useful settings. The URLs are useful information. And there will probably be things we want to add here in the future (like change privacy level).

**Comment by lorenzo-cavazzi** [comment]
In the meantime, these points were solved.

1. Collaboration will disappear for now https://github.com/SwissDataScienceCenter/renku-ui/issues/2256
2. We show whether a session is running or not through the new Connect button -- soon there will be only 1 session per project (ref: https://www.notion.so/Make-autosaves-not-be-so-bad-120264b524ce45d485d407c14a597fb6)
3. We now have a bunch of settings there
