### ISSUE TITLE
Improvements to presentation of merge request

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#854]
## Motivation

The merge request display is pretty useful, but a few small improvements would make it better.

## Proposal

* [x] Show the tabs in this order:  'Changes', 'Commits', 'Discussion'
* [x] Show notebooks and markdown files first, then the opaque files second
* [x] Like issues, we should show Open and closed in tabs
* [ ] Show markdown files side-by-side, similar to how notebooks are shown
* [ ] The card header for the sections should have an icon/link to the the diff tool in GitLab
* [ ] Don't prompt user to create a new MR for every branch. Potential MRs should be in another tab, besides Open and Closed
* [ ] Make actions obviously buttons.

(See marked-up screenshot below.)

![changes desc](https://user-images.githubusercontent.com/1196411/77302921-5f00e100-6cf2-11ea-87cf-66e79c5e0fb8.png)
![buttons](https://user-images.githubusercontent.com/1196411/90639521-11e85300-e22f-11ea-9b4f-0852e159a1e6.png)

## Additions

The _back-to-list_ button in Issues and Merge Requests should look the same as in the datasets. Instead of
![image](https://user-images.githubusercontent.com/1196411/82876343-ea882f80-9f38-11ea-9962-5fbdabe0c5c3.png)

It should look like:
![image](https://user-images.githubusercontent.com/1196411/82876393-fbd13c00-9f38-11ea-8c83-d79c3fa53141.png)

And, there should be a back-to-list button in the "New Issue" and "New Merge Request" pages, just like there is in the "New Dataset" page.

**Comment by vfried** [comment]
Regarding the style inside the tab here i decided to use a different one since it would be a different level... 

We have this as a first level....
 
![image](https://user-images.githubusercontent.com/42647877/82219113-227dea00-991d-11ea-8f9d-27a18c7231ae.png)

This as second level:
![image](https://user-images.githubusercontent.com/42647877/82219161-2d387f00-991d-11ea-87bc-8fb5b083c33c.png)

And i thought the one i chose could make a different level also...
![image](https://user-images.githubusercontent.com/42647877/82219231-42ada900-991d-11ea-9730-371d60417303.png)

Maybe we could change colors a bit to make it stand out a bit less...
![image](https://user-images.githubusercontent.com/42647877/82219563-bf408780-991d-11ea-8625-0fcefd5f73b2.png)

**Comment by ciyer** [comment]
I see the argument for having different horizontal tab styles depending on the level, but I think there is also an argument for consistency. I think we should leave it as you implemented and then discuss with the designer when he starts working on it.

**Comment by ciyer** [comment]
Made obsolete by  #1361.
