### ISSUE TITLE
Looking logged in when being logged out

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#874]
## Description

On renkulab, the UI sometimes looks as if I were logged in, but I am actually logged out (automatically, after I think a couple of hours, but I'm not so sure about the actual time, might be more).  For example:

![image](https://user-images.githubusercontent.com/4173925/77637743-704a2780-6f56-11ea-8533-e4ea971ce530.png)

-  https://renkulab.io/projects/cchoirat/renkur/
- operating system and version
![image](https://user-images.githubusercontent.com/4173925/77637883-9f609900-6f56-11ea-9e7c-c51872c673ed.png)

- browser and version
![image](https://user-images.githubusercontent.com/4173925/77637919-adaeb500-6f56-11ea-83e0-306531b6c5e2.png)
 
<details><summary>Browser Output</summary>
<pre>
If possible, paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by ciyer** [comment]
Suggestion: We pool every 10 minutes or so to see if the user is still logged in. If the user has been logged out, we show a pop-up that the you have been logged out.

**Comment by ableuler** [comment]
>Suggestion: We pool every 10 minutes or so to see if the user is still logged in. If the user has been logged out, we show a pop-up that the you have been logged out.

Maybe I misunderstand the issue and the solution is actually simpler than I think, but it seems to me that the problem comes from the fact that the login status is ambiguous. If that's true - depending on how exactly you would determine the login status - you might get a "logged-in" status and still see the behaviour observed by @cchoirat.

**Comment by lorenzo-cavazzi** [comment]
If we query the `/user` endpoint, we shouldn't get an inconsistent response, right? :thinking:
The reason for this issue is that we don't query nor refresh the user data when credentials expire. In fact, we don't even know when this happens. I believe #879 would solve the problem if we get that extra header on every response, even if it's a 2xx response. Otherwise, we may get valid responses even when the token expires, but with unexpected content (most GitLab APIs would give us valid responses, but for anonymous users).

Would it make sense to have the token expiry date from the /user endpoint? Or is that a bad practice for the security of the app?

**Comment by ableuler** [comment]
> If we query the /user endpoint, we shouldn't get an inconsistent response, right? 🤔

A valid response from `/user` means that the user has a valid session with the gateway and that this session has a valid GitLab oauth token. It's true that checking these two facts on a regular basis will probably detect a decent fraction of all possible "broken" login states. So you would just compare the login status inferred from `/user` to the ui state and display a message when the two are not consistent anymore?

**Comment by lorenzo-cavazzi** [comment]
I think that was the idea for a quickfix, but anything more robust is welcome

**Comment by lorenzo-cavazzi** [comment]
I tried this on the latest renku version on dev.
I managed to reproduce this case only when logging out from another tab and keep browsing public resources (i.e. that can be retrieved as an anonymous user). A proper fix would require a single sign out strategy

**Comment by ciyer** [comment]
#1048 is an updated version of this issue.
