### ISSUE TITLE
Complete logout circle before triggering any re-login

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#879]
Currently, whenever the UI gets a 401 response from the API, it will send the user to a login-circle. Before triggering this login-circle, the user should be logged out of all backend services to prevent inconsistent login states between the different backend services.

EDIT: we may want to add an extra header to the response whenever the UI should re-login to avoid accidentally doing that on legit 401 responses.

This will fix #874.

**Comment by lorenzo-cavazzi** [comment]
Instead of a complete logout, we could log-out selectively from some of the services.
This should solve most of the problems and limit the impact on the user (e.g. tokens on GitLab don't expire, no need to re-login there).
The `/auth/logout` backend endpoint has to be updated to support this interaction.

**Comment by lorenzo-cavazzi** [comment]
This can potentially fix inconsistencies, but it won't fix #874 because we currently don't get a `401` response in some cases (e.g. when logging out on another tab and keep querying GitLab public resources)

**Comment by ciyer** [comment]
Closing because we have a better solution for this problem: #1048.
