### ISSUE TITLE
Do not show autosave data recovery dialog for unprivileged sessions

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-ui#906]
## Description

When starting an environment which has autosaved data, UI displays a dialog to notify users that some data has been recovered. An anonymous user or a logged-in user with no developer access, 
should not see this dialog because there is nothing to recover for them. However, this dialog is still displayed for them.

## Reproduce

1. Use a dev env with has anonymous sessions enabled
1. Find a project which has autosaved data
2. Try to start an environment from that project/branch

## Context
`renku-notebooks` disables autosaving for those users (implemented in https://github.com/SwissDataScienceCenter/renku-notebooks/issues/280).

**Comment by lorenzo-cavazzi** [comment]
We can hide the autosaved branches to unprivileged users, but the autosaves will still behave in a weird way since there is no reference to the user who generated them.
This means it works fine in repos with a single maintainer/developer, but other developers would see the autosaved branch as if it was generated from them -- and it will be loaded in their environment as well.

Would it make sense to include the escaped name in the branch name as well and consider it when starting an environment? That would make the experience much better.
We may want to create separate issues for this since it has a broader impact.

**Comment by ableuler** [comment]
> Would it make sense to include the escaped name in the branch name as well and consider it when starting an environment?

Oh, I thought this was already the case. [This branch](https://renkulab.io/gitlab/covid-19/covid-19-public-data/tree/renku/autosave/ableuler/master/478549a/478549a) for example was clearly created by a while ago by a hopeful person with aspirations to do something useful with the covid-19 data...

**Comment by lorenzo-cavazzi** [comment]
ouch, you are right! I must have been blind while checking this :facepalm: 
The format appears to be `renku/autosave/<username>/<branch>/<starting_commit>/<fianl_commit> `

**Comment by ableuler** [comment]
Haha, no problem. I think the more generic issue deserves being tackled relatively soon. But I'm still fine with merging the current PR / closing this issue if you don't want to implement the checking of the name right away.

**Comment by lorenzo-cavazzi** [comment]
since all the data I need are already there, the *proper* fix should be quick -- and definetly better than the temporarily solution I prepared. I'll address it right away :slightly_smiling_face:
