### ISSUE TITLE
Improvements to dataset create

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#971]
## Motivation

I was helping a new user upload data, and it would have been nice to be able to specify the URL where the data was coming from in the dataset creation tab (instead of having to first download the data and reupload it into renkulab), which is functionality that exists in renku python. It was also unclear to the user without explanation the difference between create and import.

## Proposal

(1) It might be nice to include a short blurb about what a dataset is on the dataset add/import page with a link to the docs. E.g.:

A dataset is defined on RenkuLab as a named collection of zero or more files. The name, description, creator, creation date of the dataset, as well as the paths to all of the files that are added to the dataset, are tracked in a metadata file. If you are creating a dataset from a collection of files (either from your local machine or somewhere in the cloud), use "create". If you are importing a published dataset or a dataset from another Renku project (e.g. a set of files already with metadata, from Zenodo, Dataverse, or a Renku project), use "import".

create = "build a new dataset by filling out some metadata and uploading/importing individual data files"
import = "import a published dataset (already contains metadata) from zenodo or dataverse, or from another renku project."

(2) The `renku dataset add` command lets users specify URLs to pull data from. It would be useful to add this as an additional input box for upload.

**Comment by ciyer** [comment]
Good points. I would prefer to use different words for the action of reusing a dataset, and the action of grabbing data from a URL, rather than using "import" for both cases, since I think that is confusing.

Here is my proposal for the changes to the UI.

In both cases the "More about datasets" should be a link to the documentation.

# Changes to Dataset Create

![image](https://user-images.githubusercontent.com/1196411/86453337-e4e2ee00-bd1d-11ea-905a-a9c7e2475ede.png)

The "URL" tab should have just one field to specify a URL.

# Changes to Dataset Import

![image](https://user-images.githubusercontent.com/1196411/86453359-ee6c5600-bd1d-11ea-9948-66637a57758d.png)
