### ISSUE TITLE
Update CKEditor

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#997]
We have a new TextEditor(CKEditor), we should continue improving the way it works and add it to where it's missing.

**Comment by ciyer** [comment]
There are two problems that should be fixed as part of this issue. Either by virtue of the upgrade or, otherwise, directly.

## Cannot edit content unless switched to "Markdown" mode.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/1196411/91712682-8ce32f00-eb88-11ea-9d2c-45656f0527fd.png">

## Switching markdown on and off leads to an accumulation of toolbars

<img width="782" alt="image" src="https://user-images.githubusercontent.com/1196411/91712768-b9974680-eb88-11ea-86be-1ea5a162ade2.png">

**Comment by vfried** [comment]
Closed by #1081
